### PR TITLE
[RM Ch07] Typo Corrections in Sect. 7.10.5

### PR DESCRIPTION
**Pull request by msidana**
* Fixed table numbers - https://github.com/cntt-n/CNTT/issues/396

### CODE REVIEW

**Comment by rabi-abdel** [comment]
@ASawwaf @mbustame can you please approve this so it can be merged?

**Comment by msidana** [comment]
@mbustame Can you please approve for merging ?

**Comment by kedmison** [comment]
Sorry, @ASawwaf @bfcohen I merged this when it was RM Ops domain to do so. It was a simple one so hopefully you agree with the merge.  I will be more careful in future.

**Comment by ASawwaf** [comment]
For Sure , no worries

**Pull request merged**
