### PR TITLE
[RM Ch03] Add energy efficiency

### PR DESCRIPTION
**Pull request by xavier-grall**
This is a minimal short description of the energy efficiency for explaining the related metrics added by #3258 for fixing #3223 It may need to be further completed.

### CODE REVIEW

**Comment by walterkozlowski** [comment]
@xavier-grall and @karinesevilla: this is a good contents but we need to follow the standards related to referencing documents.  @karinesevilla can you help @xavier-grall to do this, and I will be happy to  approve.

**Comment by petorre** [comment]
Traffic/power is useful KPI but it is not "efficiency" (ratio between out and in).
Need to differentiate between average and peak.

**Comment by xavier-grall** [comment]
@walterkozlowski 
I propose some modifications for this PR in the new PR #3262 (since I cannot modifiy this one probably because i don't proceed correctly)

**Comment by walterkozlowski** [comment]
Replaced by PR#3262

**Pull request closed without merging**
