### PR TITLE
CCSO-42 Jbeltranatl csoch01 2

### PR DESCRIPTION
**Pull request by jbeltranatl**
Draft Update of Introduction

### CODE REVIEW

**Comment by jbeltranatl** [comment]
@rt063356 @mtnskiier please approve this pull request for CNTT Structure doc Introduction. Thx.

**Comment by jbeltranatl** [comment]
@mtnskiier I changed the wording. Please approve. this is just a WIP. Thx.

**Comment by jbeltranatl** [comment]
@nickchase can you approve? this is a WIP doc but Rick out today.

**Comment by rabiabdel** [comment]
merge as it has met the required two approvals.

**Pull request merged**
