### PR TITLE
[RA-1 Ch01] Add section on  OpenStack Release

### LINKED ISSUE #1229: [RA-1 Ch01]  Add OSTK Release
Currently, the Pike release is mentioned in RA-1 Ch04 and 05 but we need an upfront statement about which OSTK release this version of RA-1 conforms to,

### PR DESCRIPTION
**Pull request by pgoyal01**
Add section "CNTT OpenStack Reference Release"

Fixes #1229

### CODE REVIEW

**Comment by pgoyal01** [comment]
@iangardner22 unfortunately we are locked into a release because of the API versions and the services.

Typo: corrected. Thanks

**Comment by rabiabdel** [comment]
@karinesevilla @ASawwaf @bfcohen @walterkozlowski can you review guys please

**Comment by walterkozlowski** [comment]
Will do Rabi
Cheers
Walter

Walter Kozlowski
Architecture & Strategy Principal
Converged Cloud & Infrastructure Principal
Networks and IT
Telstra
+61 407 724 612
________________________________

**Comment by rabiabdel** [comment]
Pike! approving for now.

**Pull request merged**
