### PR TITLE
Chapter 3 refinements

### PR DESCRIPTION
**Pull request by markshostak**
Chapter 3 refinements

### CODE REVIEW

**Comment by pgoyal01** [comment]
I had already made my changes in Chapter 03 on a separate pull request #86 including some additional changes.

Best regards,
Pankaj
--------
pg683k@att.com | w  720.475.4530  |  m 720.327.0104

**Comment by xavier-grall** [comment]
My previously merged pull request #65 is partially overridden by that one: I guess it is a due to synchro issue between pull requests

**Comment by rabi-abdel** [comment]
Hi @xavier-grall Yes I noticed that. That was due to the fact that there were two Pull requests for Chapter 3 which both for approved simultaneously. Post Paris we will prevent two pull requests for the same chapter to be created simultaneously. For now, I will go through #65 and bring in your changes. Hope that is ok

**Comment by xavier-grall** [comment]
alternatively, I can also do a new pull request (if you want)

**Comment by rabi-abdel** [comment]
@xavier-grall no worries, let me do it easier and share with you to confirm.

**Comment by rabiabdel** [comment]
Closing this Pull Request as it has been incorporated within https://github.com/cntt-n/CNTT/pull/101 which will be discussed tomorrow.

**Pull request closed without merging**
