### PR TITLE
[docs] Applying Anuket theme to specification docs

### PR DESCRIPTION
**Pull request by gkunz**
This applies the Anuket (former OPNFV) theme to the Anuket
specification docs built by read-the-docs.

Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

### CODE REVIEW

**Comment by gkunz** [comment]
@CsatariGergely check the resulting rendering with this patch. It is not 100% nice yet.

**Comment by CsatariGergely** [comment]
> 
> 
> @CsatariGergely check the resulting rendering with this patch. It is not 100% nice yet.

It looks very good. I think the only missing part is the {%- block extrahead %} section from the sphinx-bootstrap theme. This makes the pop down menus on the top never popping.

**Comment by gkunz** [comment]
In the last commit, I changed the color of the links to "Anuket green" from "OPNFV green". I am wondering, though, if "Anuket blue" for normal links and "Anuket green" for hovering over links wouldn't look a bit more serious.

**Comment by CsatariGergely** [comment]
> 
> 
> In the last commit, I changed the color of the links to "Anuket green" from "OPNFV green". I am wondering, though, if "Anuket blue" for normal links and "Anuket green" for hovering over links wouldn't look a bit more serious.
> image

For me the blue for normal links and green for hovering looks very good.

**Review by pgoyal01 — APPROVED** [review]

**Comment by tomkivlin** [comment]
Where can the previews be found please?

**Review by bramwelt — APPROVED** [review]

**Comment by gkunz** [comment]
@tomkivlin the screenshot shown above is based on a local build. In principle, this is supposed to be the content from here [1] using the theme used here [2]. I am afraid I cannot point you an online version of the documentation.

[1] https://cntt.readthedocs.io/en/latest/
[2] https://docs.opnfv.org/en/latest/

**Comment by CsatariGergely** [comment]
You can checkout the pr with `gh pr checkout 2526` and then generate the docs locally with `tox -re docs`

**Review by CsatariGergely — APPROVED** [review]

**Comment by gkunz** [comment]
Hi @scottsteinbrueck, can you please review and approve?

**Comment by pgoyal01** [comment]
@walterkozlowski Can you approve?

**Comment by gkunz** [comment]
Kind review reminder. Thank you!

**Pull request merged**
