### PR TITLE
Chap-1.6 Updated NFV mapping scope image

### PR DESCRIPTION
**Pull request by markshostak**
Chap-1.6 Updated NFV mapping scope image

### CODE REVIEW

**Comment by rabiabdel** [comment]
That looks very good. @karinesevilla, @xavier-grall are you guys aligned with this update?

**Comment by pgoyal01** [comment]
Does the Reference Model include the VIM as is implied by the diagram?

**Comment by karinesevilla** [comment]
@rabiabdel, @pgoyal01
Yes agree with the picture, I think it would have been difficult to exclude the VIM of our scope

**Comment by pgoyal01** [comment]
Do we need a chapter on VIM -- essential capabilities?

**Comment by rabiabdel** [comment]
@pgoyal01 this is a great point, i think this can be part of Chapter 3. i don't think we need a whole chapter for it. if you look at some of the tables in Chapter 3, they are VIM metrics. we might just need to clarify that bu adding a third category (exposed, internal, and VIM).

**Comment by rabiabdel** [comment]
48 hours passed, i will go and approve this.

**Pull request merged**
