### PR TITLE
Chapter 5 - Sections 5.1 and 5.2

### PR DESCRIPTION
**Pull request by karinesevilla**
5.1 Introduction, modification referring to issue #140 
5.1.1 and 5.2.1, "support of flavours" removed referring to issue #145 
5.1.3 and 5.2.3, "Horizontal scaling" replaced by " NFVI scaling"

### CODE REVIEW

**Comment by pgoyal01** [comment]
@karinesevilla Couple of questions:

Section 5.1: "Depending on the requirements of VNFs, a VNFC will be deployed with a NFVI instance type and an appropriate compute flavour." What is the difference between instance type and compute flavour? 	

As you know, instance type as used by AWS and other public cloud providers differs significantly from the definition here, "A NFVI instance type is defined by a NFVI SW profile and a NFVI HW profile. " Would this cause confusion?

Would a compute flavour be used when creating an instance (VM)?

Figure 5.3: what does "HA" represent? 

Nitpick: CPU ALlocation Ratio is defined as "Number of virtual cores per physical core" -- a CPY Allocation Ratio of 1:4 would then imply 1 vCPU on 4 physical CPUs.

**Comment by karinesevilla** [comment]
@pgoyal01 
1-What is the difference between instance type and compute flavour?
The instance type (basic, network intensive, compute intensive) caracterizes a set of capabilities for a compute environment on top of which applications will run.
The compute flavour will be choosen for a specific VNF-C to fit the application requirement in terms of cpu, memory and  storage ("size").
2- I think the notion of type versus size is also present in AWS offer.
3-Would a compute flavour be used when creating an instance (VM)?
Yes 
4- For me, HA means High Availability in Figure 5.3, but I wasn't the author of the initial figure. By the way, I think that we need to translate it into features in SW profile or to remove it of the figure if we don't find features relevant features on HA.
5- CPU ALlocation Ratio 
 Yes totally agree, It must be changed to 4:1  to fit the definition

**Comment by pgoyal01** [comment]
@karinesevilla Thanks. I think the document needs to make clear the differences between instance type and flavours as this is the first they may encounter both terms.

**Comment by karinesevilla** [comment]
@pgoyal01 
Instance type and compute flavour are defined in chapter 1. If it isn't clear enough, we must modify them. I'll write an issue for chapter 1 to propose modifications.

**Pull request merged**
