### PR TITLE
Proposed edits - 4.1 Capabilities and Metrics 4.2 Catalogue

### PR DESCRIPTION
**Pull request by trevgc**
Suggested edits attempt to improve consistency of terminology and clarify certain metric definitions.  For example vCPU vs vCPU cores vs CPU cores vs cores vs physical-cores ...  should be defined and used consistently.

### CODE REVIEW

**Comment by rabi-abdel** [comment]
@markshostak please review before the meeting tomorrow.

**Comment by markshostak** [comment]
Thanks Trevor!
@rabiabdel 
- 4.1 should be ok
- 4.2 we probably can't merge live on Thursday's call, due to conflicts with existing pending changes in this section from another PR, that have not been merged yet
Thx, -M

**Comment by markshostak** [comment]
Note to self: 4.2 conflict is w/ PR #317

**Comment by markshostak** [comment]
Approved w/ edits per chapter review meeting 18/9/2019.

**Comment by xavier-grall** [comment]
Regarding, perf metrics modification in 4.1.3.1 & 4.1.5.1, I would appreciate to have a few time for discussing those changes and/or proposing other since I was the previous contributor for them (see commit https://github.com/cntt-n/CNTT/commit/5e2f38aec0ae8771bdc8872b83976fd752023a36) and that PR has been posted without preliminary and very recently (in the night before yesterday for me  in France).
Maybe those modifications on perf metrics could be put off for next release ?

**Comment by markshostak** [comment]
Hi Xavier, There was some protracted discussion about those tables in yesterday's review. The conclusion was that we need to hold a detailed review, which is scheduled for 2/10/2019. That would be a great time for you to discuss/propose changes, and I know we have some questions you can probably answer. WRT the current disposition, the team made some edits, but wanted to keep it as it is now, until the 2/10 mtg, at which point we will update it with final changes. So, the way it is now is basically temporary for Antwerp. Thanks, -Mark

**Comment by xavier-grall** [comment]
@markshostak ok thanks (i was having to leave the webex before the end)

**Pull request merged**
