### PR TITLE
[RA1 Ch4] More on NUMA-balanced IO, memory, storage

### PR DESCRIPTION
**Pull request by petorre**
... placement of NICs to get NUMA-balanced system (balancing the I/O, memory, and storage across both sockets)...

### CODE REVIEW

**Comment by petorre** [comment]
Related to #1389. (Sorry that I likely do something wrong, but there it did not allow me to Edit.)

**Comment by ASawwaf** [comment]
@peterwoerndle  ,We need to add "to avoid a cross NUMA traffic to boost the performance"

but I don't know where is the best place to add . is  cloud infrastructure or workload

**Comment by petorre** [comment]
> @peterwoerndle ,We need to add "to avoid a cross NUMA traffic to boost the performance"
> 
> but I don't know where is the best place to add . is cloud infrastructure or workload

Added "to avoid crossing interconnect between CPUs".

**Comment by ASawwaf** [comment]
@peterwoerndle , I reword it "NUMA-CPU alignment" instead of NUMA setting

**Comment by petorre** [comment]
> @peterwoerndle , I reword it "NUMA-CPU alignment" instead of NUMA setting

I would keep it simply as "NUMA settings" because:
- NUMA is also for IO and memory.
- Used CPUs will be on their NUMA node.

**Comment by petorre** [comment]
(Moving changes to #1389 that I can edit again, please comment/change further there, I'm closing this PR.)

**Pull request closed without merging**
