### PR TITLE
RA2 Ch6 - update status

### PR DESCRIPTION
**Pull request by tomkivlin**
IFO -> SDC

### CODE REVIEW

**Comment by rabiabdel** [comment]
> I see here only a minor change, which I approve.
> 
> Not related to this PR, but #894: I see that the updates by Samuel M. (eg moving a lot text from 6.15 under 6.14) and my updates as agreed with Samuel M. yesterday (removing 6.16 and replacing it with modified text into 6.15; as well as my texts under 6.11) did not merge into main branch earlier.

@samulikuusela would it be possible to create a PR for the proposed change (create a fresh PR), we can get it approved and merged before Sneka. Otherwise, create an issue for it and it can be handled first thing after Snezka. Your call.

**Comment by rabiabdel** [comment]
Since this is very minor change, it will be "Force Merged".

**Comment by samulikuusela** [comment]
> > I see here only a minor change, which I approve.
> > Not related to this PR, but #894: I see that the updates by Samuel M. (eg moving a lot text from 6.15 under 6.14) and my updates as agreed with Samuel M. yesterday (removing 6.16 and replacing it with modified text into 6.15; as well as my texts under 6.11) did not merge into main branch earlier.
> 
> @samulikuusela would it be possible to create a PR for the proposed change (create a fresh PR), we can get it approved and merged before Sneka. Otherwise, create an issue for it and it can be handled first thing after Snezka. Your call.



> > I see here only a minor change, which I approve.
> > Not related to this PR, but #894: I see that the updates by Samuel M. (eg moving a lot text from 6.15 under 6.14) and my updates as agreed with Samuel M. yesterday (removing 6.16 and replacing it with modified text into 6.15; as well as my texts under 6.11) did not merge into main branch earlier.
> 
> @samulikuusela would it be possible to create a PR for the proposed change (create a fresh PR), we can get it approved and merged before Sneka. Otherwise, create an issue for it and it can be handled first thing after Snezka. Your call.

@rabiabdel ok I will create an issue within a few days, because right now I won't be able to work any longer today.

**Comment by rabi-abdel** [comment]
> > > I see here only a minor change, which I approve.
> > > Not related to this PR, but #894: I see that the updates by Samuel M. (eg moving a lot text from 6.15 under 6.14) and my updates as agreed with Samuel M. yesterday (removing 6.16 and replacing it with modified text into 6.15; as well as my texts under 6.11) did not merge into main branch earlier.
> > 
> > 
> > @samulikuusela would it be possible to create a PR for the proposed change (create a fresh PR), we can get it approved and merged before Sneka. Otherwise, create an issue for it and it can be handled first thing after Snezka. Your call.
> 
> > > I see here only a minor change, which I approve.
> > > Not related to this PR, but #894: I see that the updates by Samuel M. (eg moving a lot text from 6.15 under 6.14) and my updates as agreed with Samuel M. yesterday (removing 6.16 and replacing it with modified text into 6.15; as well as my texts under 6.11) did not merge into main branch earlier.
> > 
> > 
> > @samulikuusela would it be possible to create a PR for the proposed change (create a fresh PR), we can get it approved and merged before Sneka. Otherwise, create an issue for it and it can be handled first thing after Snezka. Your call.
> 
> @rabiabdel ok I will create an issue within a few days, because right now I won't be able to work any longer today.

offcourse no problem. Samuel and I have created this for it (https://github.com/cntt-n/CNTT/pull/930), I will keep it open and you can edit it to make sure your Changes are in there. Rabi

**Pull request merged**
