### PR TITLE
[TSC]: Updated Milestone diagram/table

### PR DESCRIPTION
**Pull request by prabhubalan**
Updated with some more details in the milestones diagram and detailed out in the milestone table. Each row in the milestone table can be mapped against the milestone diagram. Also it explains what are the activities to be completed in between each phase or stages.

### CODE REVIEW

**Comment by prabhubalan** [comment]
> The general flow is very good. I propose two changes:
> 
> 1. Replace "CNTT is single-release vehicle for all projects" (which is too ambiguous) by a more precise statement like "Each CNTT release is the only delivery vehicle and is common for all projects".
> 2. Content Review Freeze (M4) description contains the same wording as the previous stage (Contents Review): " to carefully review and validate the contents and check for errors in the document", which will create confusion. I propose changing the description of M4 to: "The goal is to perform the final proof reading of the document before it is released. This is the release content completion milestone." I think that the term "proof reading" is self-explanatory.

Thanks @walterkozlowski for the proposed change. I have updated it now. The content in point 1 was not changed in this PR. It was the original content of my previous PR. I have updated them now.

**Comment by prabhubalan** [comment]
> Can you align the titles in the diagram with the titles of the detailed milestones?

@xmulligan  - Sorry, I didn't get you. What do you mean by align the titles?

**Comment by xmulligan** [comment]
@prabhubalan the M1, M2, ect titles in the image do not match the titles under the "Review" section in the table

**Comment by prabhubalan** [comment]
@xmulligan - I could see there are minor changes only Scope Changes (Scope Changes/Logging) and Release End. Please review and point me if there are any.

**Pull request merged**
