### PR TITLE
[RA2Ch02] Removing hyperthreading

### LINKED ISSUE #1731: [RA2 Ch02] Removing hyperthreading

### PR DESCRIPTION
**Pull request by EditKoselak**
Closes #1731

### CODE REVIEW

**Comment by tomkivlin** [comment]
@EditKoselak - what is the reason for the change?  The HT requirement is pulled through from the Reference Model.  Is there a reason why you think this isn't applicable to Kubernetes deployments?

**Comment by EditKoselak** [comment]
> @EditKoselak - what is the reason for the change? The HT requirement is pulled through from the Reference Model. Is there a reason why you think this isn't applicable to Kubernetes deployments?

It is applicable but HT is an Intel-specific term while SMT is the generic term for the technology.

**Comment by tomkivlin** [comment]
> > @EditKoselak - what is the reason for the change? The HT requirement is pulled through from the Reference Model. Is there a reason why you think this isn't applicable to Kubernetes deployments?
> 
> It is applicable but HT is an Intel-specific term while SMT is the generic term for the technology.

Ah OK I understand - in that case can you also raise a PR to modify the Reference Model (if you haven't already) and we can look to merge this one once the RM is updated, just to ensure traceability.

**Comment by EditKoselak** [comment]
> > > @EditKoselak - what is the reason for the change? The HT requirement is pulled through from the Reference Model. Is there a reason why you think this isn't applicable to Kubernetes deployments?
> > 
> > 
> > It is applicable but HT is an Intel-specific term while SMT is the generic term for the technology.
> 
> Ah OK I understand - in that case can you also raise a PR to modify the Reference Model (if you haven't already) and we can look to merge this one once the RM is updated, just to ensure traceability.

Thanks for the comment! I think #1699 covers that, could you please check if this is what you had in mind?:)

**Comment by tomkivlin** [comment]
> > > > @EditKoselak - what is the reason for the change? The HT requirement is pulled through from the Reference Model. Is there a reason why you think this isn't applicable to Kubernetes deployments?
> > > 
> > > 
> > > It is applicable but HT is an Intel-specific term while SMT is the generic term for the technology.
> > 
> > 
> > Ah OK I understand - in that case can you also raise a PR to modify the Reference Model (if you haven't already) and we can look to merge this one once the RM is updated, just to ensure traceability.
> 
> Thanks for the comment! I think #1699 covers that, could you please check if this is what you had in mind?:)

Perfect - thanks!

**Pull request merged**
