### PR TITLE
[RA1 Ch07] ToC and first outline for Chapter 7

### PR DESCRIPTION
**Pull request by karinesevilla**
Resolving issue #369 
Proposal of ToC and outline to start "Operations and LCM" chapter

### CODE REVIEW

**Comment by rabi-abdel** [comment]
@bfcohen please approve if you are OK with this.

**Comment by pgoyal01** [comment]
@karinesevilla Should 7.3 include provisioning of host aggregates, post configuration of compute nodes (per profile types)? Is there a decision table on how many compute nodes to be configured per profile type?

**Comment by rabi-abdel** [comment]
@karinesevilla can you please address @pgoyal01 comment?

**Comment by karinesevilla** [comment]
@pgoyal01 I agree we should add provisioning of host aggregates and post configuration of compute nodes, for 7.3. Would you like to add it?

**Comment by karinesevilla** [comment]
@pgoyal01 new commit including your comment about section 7.3

**Pull request merged**
