### PR TITLE
[RA-1 Ch04] Update Figure 4-1

### LINKED ISSUE #926: [RA-1 Ch04] Figure 4-1
Based on feedback from multiple folks (@mbustame, @mf4716, @markbeierl) modify diagram and provide network descriptions.

### PR DESCRIPTION
**Pull request by pgoyal01**
[RA-1 Ch04] @iangardner22 Updated Figure 4-1 and added network descriptions
(I am making the changes on behalf of @iangardner22)

Fixes #926

### CODE REVIEW

**Comment by markbeierl** [comment]
Looks good.  Can we get the source .ppt added too in case anyone else wants to update this in the future?

**Comment by tomkivlin** [comment]
I'm happy to review, but did you mean to add me as a reviewer?

**Comment by markbeierl** [comment]
Controller and compute nodes should not be on the storage management network.  That is for Ceph replication only and would bog down the networks for the compute nodes.

**Comment by pgoyal01** [comment]
@markbeierl Thanks. Corrected.

@tomkivlin Yes please

**Comment by markbeierl** [comment]
I cannot seem to approve this.  Does someone need to add me as a reviewer?

**Comment by markbeierl** [comment]
Also is the image in this PR twice, in two different directories?

**Comment by mf4716** [comment]
> I cannot seem to approve this. Does someone need to add me as a reviewer?

@markbeierl - I couldn't add you, but I did add Mark S., reached out to @mbustame (Mike), and I approved.

**Comment by markbeierl** [comment]
Extraneous file in PR should be removed:  doc/ref_arch/figures/Figure_4_1_OpenStack_Network_Layout_20200110.png

Can we get the PPT source added?

**Comment by iangardner22** [comment]
@markbeierl thank you for the correction on the Storage Management...!  Appreciated

**Comment by iangardner22** [comment]
Thanks a lot for the approvals and big thanks to @pgoyal01 for raising this!

**Comment by pgoyal01** [comment]
@markbeierl Thanks for pointing out the extraneous file -- will open issue and delete. The source files were added yesterday prior to the merge [CNTT_diagrams.pptx.](https://github.com/cntt-n/CNTT/blob/master/artefacts/CNTT_diagrams.pptx)

**Pull request merged**
