### PR TITLE
[TSM] Define Technical Contribution Metrics

### PR DESCRIPTION
**Pull request by rabi-abdel**
For Fairer, More transparent method, we would like to collect the metrics of which the community feel reflective of the great work made by everybody.

Fixes https://github.com/cntt-n/CNTT/issues/1382

### CODE REVIEW

**Comment by rabiabdel** [comment]
Please provide feedback and suggestions.

**Comment by pgoyal01** [comment]
May I suggest that the TSC specify the Goal and some justification, and then task a small WG charged with defining in a methodical manner to define the measures etc. that help achieve the Goal.

Personally, this topic is not of interest to me.

**Comment by tomkivlin** [comment]
> May I suggest that the TSC specify the Goal and some justification, and then task a small WG charged with defining in a methodical manner to define the measures etc. that help achieve the Goal.
> 
> Personally, this topic is not of interest to me.

I agree. If this is a means to an end, it's not clear what that end is other than individuals being able to justify the time spent on CNTT (but even that is tenuous).  More useful, I think, would be business metrics relating to the goals of CNTT such as TCO reduction, reduction in end-to-end certification time, etc.

If we do have to go to "implementation" metrics then I would suggest things that we think will contribute to those business metrics such as number of tests contributed (in total, not per company or individual), number of conformant vendor implementations, etc.

And finally if we do have to measure levels of contribution then let's do the number of contributions as a community to show how the community is growing, rather than measuring the "effort" of individuals.

**Comment by tomkivlin** [comment]
Also - why are we tracking the number of lines etc. for Airship? Isn't that governed elsewhere? And if Airship, why not e.g. kubeadm or whichever installer we choose in RI2?  I don't understand the logic I'm afraid.

**Comment by iangardner22** [comment]
I have no strong opinion on this - except agree it needs to represent true effort spent and sometimes that effort isn't reflected in github commits or reviews.   I will accept the majority view on this one.

**Comment by ulikleber** [comment]
I am just a bit confused why we have metrics about OPNFV projects. I would understand if we have metrics for our own workstreams.

**Comment by karinesevilla** [comment]
I also think that the goal of these metrics must be clearly described and that focusing too much on these metrics can be counterproductive in term of quality.

Now, if metrics must be provided, regarding documentation, I think that the metrics we use don't reflect enough the collaborative part of work. I consider it is important to associate co-authors to commits when text is written by several authors or in the case of valuable reviews and contributions improving the PRs.
This can be done in Github, but we must be sure then that it's taken into acount when processed by analytics.

**Comment by collivier** [comment]
I will be very cautious regarding the current content of the website as it classifies users and companies. By its nature, the rankings defacto require trustable and agreed criteria.

Here we would also separate the metrics and the rankings (or filters).

We commonly select two metrics in the open source projects (LFN, OpenStack, etc.): commits and reviews. Commits mostly highlight the most active developers and reviews the core (aka key) developers (they could be the same). They are commit rankings everywhere. Reviews are mostly used for the promotions to Core Developers.

As mentioned during the governance meeting, the processes in CNTT are incorrect to fairly count the commits:
- all single commits in PRs were merged as they were and now they are squashed in a single commit
- most contributor doesn’t add the Co-Author-By label to list all people working on the change (Co-writers or very good reviews)

My understanding is that the project management (PTL in opensource) doesn’t need a specific metric in open source. Following the meritocratic model, PTL is usually elected from the core developer list.
And if we apply the right PR management in CNTT, the PRs will simply duplicate the commits.

Community message seems unclear and possibly unlinked to the contribution effort (meeting invitations on mailing lists?).

Yes OPNFV already counts the commits
Of course Functest includes changes for all and not only for CNTT but we can hardly evaluate the right numbers without too much tags and processes (and then human errors).

**Comment by walterkozlowski** [comment]
My understanding is that the overall goal is to encourage the community to participate.  The question is whether publication of these metrics will do the trick.  As with any such metric, everybody will have a different opinion on such metrics. Most likely there is no set of metrics which will be completely informative and completely fair at the same time.  For example, I do not think that the currently proposed set of metrics would show a fair measure of great efforts by @rabiabdel!  My suggestion is that this topic needs to be thoroughly thought through. Wrong way of doing this may lead to results contrary to our intentions.

**Comment by tomkivlin** [comment]
Couldn't agree more @walterkozlowski - the law of unintended consequences!

@rabi-abdel - feels to me from this thread that before we define what the metrics are we want to track, we need to define the desired outcomes, the overall goal.  Pointing out who has made the higher number of commits and which company they work for isn't going to help prove CNTT is valuable (I can see how the individuals and companies would use it as justification, but that's not the goal here, is it?)

**Comment by rabi-abdel** [comment]
> Couldn't agree more @walterkozlowski - the law of unintended consequences!
> 
> @rabi-abdel - feels to me from this thread that before we define what the metrics are we want to track, we need to define the desired outcomes, the overall goal. Pointing out who has made the higher number of commits and which company they work for isn't going to help prove CNTT is valuable (I can see how the individuals and companies would use it as justification, but that's not the goal here, is it?)

@tomkivlin @walterkozlowski @collivier @pgoyal01 @ulikleber @karinesevilla agree with all comments. I suspected this PR will be controversial. I suggest closing this PR and have the topic discussed during TSM meeting. 

For me, it is very simple, we have been given a question by Governance: 

> **What are the metrics we need to show in the Dev analysis tool LFN is using?** 
they are currently showing some metrics that the general feeling was that they are not representing the contributions made.  do we NOT need to influence what metrics are shown?

**Comment by walterkozlowski** [comment]
@rabi-abdel I agree with closing and having a TSM discussion on what we want to achieve

**Comment by pgoyal01** [comment]
I will caution against the use of lines of code in any metrics. Some folks write a single short to the point sentence while someone else writes multiple lines that really do not say anything.

**Comment by rabi-abdel** [comment]
ok I will remove this Pull Request as I don't see a straight forward way to resolve it. we will continue giving LFN feedback about what we would like to be displayed. thanks all for feedback.

**Pull request closed without merging**
