### PR TITLE
[RC Ch3] Add TST009 benchmarking to the Dataplane section

### LINKED ISSUE #1133: [RC] Need to add performance testing in RC for NFVi badging.
More compelling compliance & Verification basis comes from including performance testing with well defined specifications and success criteria: #1120, #1115

### PR DESCRIPTION
**Pull request by LucProvoost**
Fixes #1133

### CODE REVIEW

**Comment by trevgc** [comment]
VMTP and Shaker are extremely limited as data-plane performance test tools and not suitable for performance tests used in a certification program. Test cases should reference established benchmark specifications and methods for virtual environments (such as TST009) and stand-alone tools/methods need to be established in CNTT as part of the infrastructure certification test tool chain.

**Comment by mf4716** [comment]
Added additional reviewers.

@LucProvoost , (Luc) this looks good.  Waiting for others to review/comment.

**Comment by rabiabdel** [comment]
@LucProvoost @mf4716 is there an issue this relates to?

**Comment by collivier** [comment]
@trevgc I disagree on your comment about VMTP and Shaker not suitable for Certification Program.

@LucProvoost @rabi-abdel @mf4716 I don't understand the new structure of RC. For my understanding, it's in the middle of test cases already executed in RC cookbook. I think a step is missing before that and this tools and the methodology could have been described in the appropriate section (https://cntt-n.github.io/CNTT/doc/ref_cert/lfn/chapters/chapter04.html#4.2). Even once the test case is integrated, we could rather consider a specific section for the next steps to separate the two different dataplane benchmarking approaches.

**Pull request merged**
