### PR TITLE
update RI2 chapter 02 to add more requirements from RA2 Lakelse

### PR DESCRIPTION
**Pull request by xudan16**
Issue #2858

### CODE REVIEW

**Comment by xudan16** [comment]
> 

@pgoyal01 Do you mean the network intensive profile? I have checked the RA2 latest docs and there are still many descriptions about network intensive profile in the details of many requirements.

**Comment by xudan16** [comment]
> @xudan16 Can you open an issue against RA2 to correct those instances where the network profile is still mentioned. As you can see from [RM Section 2.4](https://cntt.readthedocs.io/en/latest/ref_model/chapters/chapter02.html#profiles-top-level-partitions) the network profile is no longer defined but instead, we have High Performance profile. Thanks.

@pgoyal01  I have checked the RM docs of Kali and Lakelse, it is always the High Performance (including compute/storage/network intensive). Why RM2 still mention it as network intensive profile for these 2 releases?

Since RI2 are based on RM2 Lakelse version, could we keep it as what it is now in this release? And in next release, we will update the docs as soon as RM2 updates. Is it make sense?

**Comment by xudan16** [comment]
> @xudan16 Can you open an issue against RA2 to correct those instances where the network profile is still mentioned. As you can see from [RM Section 2.4](https://cntt.readthedocs.io/en/latest/ref_model/chapters/chapter02.html#profiles-top-level-partitions) the network profile is no longer defined but instead, we have High Performance profile. Thanks.

@pgoyal01  I have checked the RM docs of Kali and Lakelse, it is always the High Performance (including compute/storage/network intensive). Why RA2 still mention it as network intensive profile for these 2 releases?

Since RI2 are based on RA2 Lakelse version, could we keep it as what it is now in this release? And in next release, we will update the docs as soon as RM2 updates. Is it make sense?

**Comment by rgstori** [comment]
> > @xudan16 Can you open an issue against RA2 to correct those instances where the network profile is still mentioned. As you can see from [RM Section 2.4](https://cntt.readthedocs.io/en/latest/ref_model/chapters/chapter02.html#profiles-top-level-partitions) the network profile is no longer defined but instead, we have High Performance profile. Thanks.
> 
> @pgoyal01 I have checked the RM docs of Kali and Lakelse, it is always the High Performance (including compute/storage/network intensive). Why RA2 still mention it as network intensive profile for these 2 releases?
> 
> Since RI2 are based on RA2 Lakelse version, could we keep it as what it is now in this release? And in next release, we will update the docs as soon as RA2 updates. Is it make sense?
> 
> @xudan16 can you work with the RA2 Workstream on this? @rgstori Can this be addressed quickly?

yes we have issue #2889, I'll prioritise this

**Comment by xudan16** [comment]
@pgoyal01 @rgstori, will update the doc when RA2 complete the udpates.

**Comment by michaelspedersen** [comment]
Looked through the added requirements, and all seems good from an RI2/Kuberef perspective. But as noted in previous comments we should wait for updated references (profiles)

**Comment by xudan16** [comment]
> Looked through the added requirements, and all seems good from an RI2/Kuberef perspective. But as noted in previous comments we should wait for updated references (profiles)

Already updated by replacing Network Intensive to High Performance.

**Review by gkunz — APPROVED** [review]

**Comment by rgstori** [comment]
hi @xudan16 just wanted to let you know that #2895 was merged - RA2 now only refers to the "High Performance" profile

**Comment by gkunz** [comment]
Hi @xudan16, sorry for causing extra effort by reformatting the table.

**Comment by xudan16** [comment]
Hi @gkunz, it's ok.
Hi @rihabbanday, @michaelspedersen and @steelescotr, let's review and try to merge this PR soon.

**Review by rihabbanday — APPROVED** [review]

**Review by pgoyal01 — APPROVED** [review]

**Comment by pgoyal01** [comment]
@walterkozlowski This is ready for you

**Pull request merged**
