### PR TITLE
Chapter 04 (based on comments (Re Issue# 32)) 

### PR DESCRIPTION
**Pull request by rabiabdel**
Addressing Comments form @hdamker, @ASawwaf, @TommyKTheDJ

Issue: https://github.com/cntt-n/CNTT/issues/32

### CODE REVIEW

**Comment by rabiabdel** [comment]
@hdamker: 
Text Changed to:
Infrastructure exposes set of capabilities, metrics, compute flavours, interface options, storage extensions, and acceleration capabilities to VNFs. Those are offered to VNFs in form of instance types with their corresponding options and extensions.

@hdamker, @ASawwaf, @TommyKTheDJ: CEPH distributed sotrage removed.

**Comment by hdamker** [comment]
I'm supporting Rabi's version, would just slightly change it to make the reference clear:

"Infrastructure exposes set**s** of capabilities, metrics, compute flavours, interface options, storage extensions, and acceleration capabilities to VNFs. Those **sets** are offered to VNFs in form of instance types with their corresponding options and extensions."

Shortly checked: "instance types" is mainly used by Amazon AWS, but as it is also a generic term, that's fine for me.

**Comment by pgoyal01** [comment]
Herbert,
That is fine. We need a definition of instance types -- it is not a term that is currently being used in the document.  Could we then replace "flavours" by "Instance Types" -- much simpler then using NFVI Software Profile or Configuration?

**Comment by rabiabdel** [comment]
Hi @hdamker : I have updated the text to reflect your suggestion above.
@pgoyal01 : Agree, i like your suggestion. let me think about it and propose something.

**Pull request merged**
