### PR TITLE
Contribution Guidelines

### PR DESCRIPTION
**Pull request by rabi-abdel**
Regarding issue: https://github.com/cntt-n/CNTT/issues/430

### CODE REVIEW

**Comment by rabi-abdel** [comment]
This will be discussed during today's technical steering meeting based on latest discussion.

**Comment by rabi-abdel** [comment]
as discussed in the meeting, we will give it 2 business days and then approve/merge

**Comment by pgoyal01** [comment]
@rabi-abdel Couple of observations/suggestions:
1. Related to Pull Requests (PR): May I suggest that we strengthen the language to include a PR must only add/change content related to the issue associated with the PR.
2. "If WSL is the person who is creating the PR, he needs to request an additional from the committers list" suggest changing to "The person creating the PR content cannot be an approver. If WSL created the PR content, then the WSL needs to request an alternate approver, preferably co-lead, from the committers list."
3. Add, "The approvers should be distributed equally among operators and vendors. For example, if WSL is an operator, then the other approver, in case of 2 approvers, should be from a vendor."
4. May I suggest that we use the criteria for 2 approvers for "minor" and 4 approvers for "major" changes.
Thanks

**Comment by rabi-abdel** [comment]
@pgoyal01 text was updated to reflect your points. if no further feedback received, I will mere by EOD today.

**Comment by pgoyal01** [comment]
@rabi-abdel Thanks. May I suggest replacing "he" in "If WSL is the person who is creating the PR, he needs to request an alternate approver, preferably a co-lead or from the committers list" by either "(s)he" or "WSL."

**Comment by rabi-abdel** [comment]
Ok. Will merge now and change the setting on GitHub to reflect this.

**Pull request merged**
