### PR TITLE
[RI] Fix Release (last minute merge)

### PR DESCRIPTION
**Pull request by collivier**
It fixes the last side effect created by [1] which should have been
rebased prior to merge.

[1] https://github.com/cntt-n/CNTT/commit/3c365155f7062da8a0150b1d8b819a763bb801d0

Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>

### CODE REVIEW

**Comment by collivier** [comment]
@rabi-abdel @rabiabdel @markbeierl @mf4716 
We are all learning about the opensource processes. Normally such a change won't have been released just before the release in many projects.
I understand we can make exceptions (at least for this one) but it should have been rebased vs master before merge to avoid all the side effects to the other parts. I will check all the side effects but this pull request should be quickly merged and applied to the release.

**Comment by rabi-abdel** [comment]
> @rabi-abdel @rabiabdel @markbeierl @mf4716
> We are all learning about the opensource processes. Normally such a change won't have been released just before the release in many projects.
> I understand we can make exceptions (at least for this one) but it should have been rebased vs master before merge to avoid all the side effects to the other parts. I will check all the side effects but this pull request should be quickly merged and applied to the release.

@collivier Thanks for doing this. let us take about it more in Prague and understand your views. it will be good to get your experience on this and apply it to CNTT. agree, we all learning how to do everything efficiently.

**Comment by rabi-abdel** [comment]
This is a fix, will apply it to release now

**Comment by collivier** [comment]
@rabi-abdel 
Yes we can discuss in Prague how to ease the Editor life.
I'm very surprised that Github allows this error which should have been detected as a conflict from my understanding. The first change was right from its tree but couldn't be merged once the first one was merged. Maybe it's just due to the manual postprocessing required for the release.

**Comment by collivier** [comment]
Thank you for the extra work!

**Pull request merged**
