### PR TITLE
[RM CH02] Update profile image

### PR DESCRIPTION
**Pull request by ASawwaf**
Update profile image

### CODE REVIEW

**Comment by ASawwaf** [comment]
https://github.com/cntt-n/CNTT/issues/1715
and add edge profile

**Comment by ASawwaf** [comment]
@CsatariGergely done

**Comment by rabi-abdel** [comment]
source image is here: https://github.com/cntt-n/CNTT/pull/1726

**Comment by ASawwaf** [comment]
@rabi-abdel thx  , it is uploaded , 

@CsatariGergely  your approval

**Comment by ASawwaf** [comment]
@Karimrabie @petorre @CsatariGergely @rabi-abdel 

Please approve

**Comment by rabi-abdel** [comment]
@ASawwaf please advice what would you like to do with this PR. based on the conclusion of last meeting to add extensions to NI profile, shall this PR be closed now?

**Comment by ASawwaf** [comment]
Thanks for your contribution as agreed last week, we will look on Profile capabilities in ch04 and figure out which one will be used in Edge use cases so no need for edge profiles

**Pull request closed without merging**
