### PR TITLE
[Gov Ch04] Nomination and Selection

### PR DESCRIPTION
**Pull request by rabi-abdel**
to start wroking on #489 #490 #491 #492 #493 #494 #496 #497 #498 #504

### CODE REVIEW

**Comment by rabi-abdel** [comment]
b4 I continue the content, let me know if ToC is OK with everybody.

**Comment by fuqiao123** [comment]
looks good to me

**Comment by rabi-abdel** [comment]
> looks good to me

@fuqiao123 you need to hit "Approve" to be marked as Approved.

**Comment by rabiabdel** [comment]
will merge and start filling the information

**Comment by rabi-abdel** [comment]
@jbeltranatl you are the code owner (can you please review and merge if you are happy with it)

**Pull request merged**
