### PR TITLE
Update references.rst

### PR DESCRIPTION
**Pull request by walterkozlowski**
Amended references as a result of GSMA/RM review

### CODE REVIEW

**Review by pgoyal01 — APPROVED** [review]

**Review by steelescotr — APPROVED** [review]

**Review by collivier — CHANGES_REQUESTED** [review]
We must rather dump the common section needed by RM into RM RST. Else there is still a gap between docx where is the file is **manually** dumped and source where it's a link to somewhere else.
Please follow what RA1 did for the full automation. It's far better.

**Comment by collivier** [comment]
In a long run, common will be deleted.

**Comment by walterkozlowski** [comment]
@collivier, yes - perhaps in long run. This is 'now and here" situation.

**Comment by collivier** [comment]
@walterkozlowski "now and here" solution should be to dump the content in RM as RA1 did.
Let's later when we could delete common.

**Comment by walterkozlowski** [comment]
@collivier, I do not want us to loose these updates, so I want this PR to be merged.
I am OK with creating a new PR, to move (I would not say dump, sorry) separate list of references for RM.

**Review by karinesevilla — APPROVED** [review]

**Pull request merged**
