### PR TITLE
Update chapter08.md

### PR DESCRIPTION
**Pull request by bfcohen**
Added some starting content to explain the role of security in the NFVi model and architecture.  I have a couple of starting pictures as well.  Got to get used to this interface. :-(

### CODE REVIEW

**Comment by manamsamuel** [comment]
Hi Beth,
I will like to add more contents to the common standards;
a) Networking Security Zoning
b) VNF Image Scanning / Signing
c) Encryption
d) Platform Patching
e) Boot Integrity Measurement (TPM)

**Comment by bfcohen** [comment]
Agree.  Some go into each of the three responsibility buckets.

**Comment by rabiabdel** [comment]
What is the next step for this @bfcohen ? are you taking feedback and incorporating them?

**Comment by bfcohen** [comment]
Yes.  I will.  I am struggling with the tools.

**Comment by manamsamuel** [comment]
Hi Rabi/Beth,
Apologies, I'm in all day workshop since yesterday but was planning to add these tomorrow.

**Comment by bfcohen** [comment]
Thank you Manam.  I have your edits and am adding them.

**Pull request closed without merging**
