### PR TITLE
[RA2 Ch06] Update chapter06.md

### PR DESCRIPTION
**Pull request by rabi-abdel**
@samulikuusela proposed text.

Fixes https://github.com/cntt-n/CNTT/issues/928

### CODE REVIEW

**Comment by rabi-abdel** [comment]
@samulikuusela I discussed this with @manamsamuel and he proposed the Changs above, if you are OK with these, please approve. Also, Feel free to update the text directly if you still have more proposed text to add.

**Comment by rabi-abdel** [comment]
@manamsamuel @samulikuusela are you guys still working on this PR or shall I close it? my assumption will be that new PRs will come as a result of the ongoing discussion and it is OK to close this for now? or shall I merge this one?

**Comment by manamsamuel** [comment]
@rabi-abdel I would say close this but I will let @samulikuusela to comment on this.

**Comment by rabiabdel** [comment]
OK, nothing was heard from @samulikuusela. following the process of assuming consenses and agreement if no objection received within 48 hours.

**Pull request closed without merging**
