### PR TITLE
[RA2 Ch02] add support for OCI compatable artefact repository

### LINKED ISSUE #1108: [RA2 Ch02 - Ch03] Add support for artefact repository APIs
from #1084

On a related note, should this also be moved as a requirement under API. Something like "The Architecture must support the usage of an OCI compatible artefact repository.

The RA needs some way to support and manage artefacts, but shouldn't be dependent upon a particular implementation.

### PR DESCRIPTION
**Pull request by xmulligan**
to fix #1108

### CODE REVIEW

**Comment by rabiabdel** [comment]
@xmulligan is it OK please to resolve conflict?

**Comment by xmulligan** [comment]
> @xmulligan is it OK please to resolve conflict? and fix seq# on the way

I'm sorry, I don't understand exactly what you are asking

**Comment by tomkivlin** [comment]
> > @xmulligan is it OK please to resolve conflict? and fix seq# on the way
> 
> I'm sorry, I don't understand exactly what you are asking

There is a merge conflict that needs resolving: https://github.com/cntt-n/CNTT/pull/1109/conflicts

**Comment by xmulligan** [comment]
sorry missed that, should be fixed now

**Pull request merged**
