### PR TITLE
[RC1 - Ch03] Documentation Updates - Clarify Statements for Excluded Test Cases

### LINKED ISSUE #1162: [RC1 - Ch03] Documentation Updates - Clarify Statements for Excluded Test Cases
Documentation clarification/updates needed:

1. Remove extra N in chapter title, "NNFVI Test Cases and Traceability to CNTT Requirements"

2. Expand, or clarify the statement, "test names must not be executed" for the following sections:
- 3.3.4.1 Identity - Keystone
- 3.3.4.2 Image - Glance
- 3.3.4.3 Block Storage - Cinder
- 3.3.4.4 Object Storage - Swift
- 3.3.4.5 Networking - Neutron
- 3.3.4.6 Compute - Nova

**Change** "According to [RA1 Core OpenStack Services APIs]({{ "/doc/ref_arch/openstack/chapters/chapter05.html" | relative_url }}) the following test names must not be executed:" 

**To** According to [RA1 Core OpenStack Services APIs]({{ "/doc/ref_arch/openstack/chapters/chapter05.html" | relative_url }}) the following tests will be excluded as there is no corresponding mandatory requirement for the feature/capability in RA-1, or there is a known issue with the feature/capability prohibiting execution:

3. Repeat sections in 2, and update the subsequent column headers with more clarity re: Exclusion, and Reason.
a) change "test rejection regular expressions" to "Excluded Test (expression reference)"
b) change "reason" to "Optional in RA-1 requirement, or Known Issue"

### PR DESCRIPTION
**Pull request by mf4716**
Fixes #1162 

Documentation updates to clarify rational for excluded tests, expand on reasons for exclusions, and correct spelling of chapter title.

Also, apply cosmetic change to Dataplane benchmarking section label from incorrect 5.3.6 value to correct 3.3.6 value.

### CODE REVIEW

**Comment by mf4716** [comment]
> tempest selects rejection/black regexp which matches the first proposal.
> https://docs.openstack.org/tempest/latest/run.html
> 
> I would consider reason as better too.
> 
> Would you mind only fixing the typo?

Please edit & commit change directly to this PR.   Or, please provide exact line #(s) and verbiage to change(add)?

**Comment by mf4716** [comment]
> Please format correctly the tabs as it was.

@collivier - Source-diff might show an offset, but Rich-diff looked accurate.  Regardless, I revised table (tabs) to better align column delimiters as viewed in Source-diff for the following sections:

3.3.4.1 Identity - Keystone - done
3.3.4.2 Image - Glance - done
3.3.4.3 Block Storage - Cinder - done
3.3.4.4 Object Storage - Swift - done
3.3.4.5 Networking - Neutron - done
3.3.4.6 Compute - Nova - done

**Comment by rabiabdel** [comment]
@collivier @mkr1481 please re-review

**Comment by mf4716** [comment]
@collivier @mkr1481 please re-review

**Comment by mf4716** [comment]
Team, please review/comment/approve.  Thank you.

**Comment by mf4716** [comment]
@karinesevilla @pgoyal01 @rrajesh70 @rabi-abdel @collivier @mkr1481 

Work was completed 10 days ago.  

Can we please review/approve so we can close this issue?

Thanks in advance.

**Comment by mf4716** [comment]
@collivier , all changes made were cosmetic, and all were incorporated into the current version, with the exception if you could please address:

"tempest selects rejection/black regexp which matches the first proposal.
https://docs.openstack.org/tempest/latest/run.html

I would consider reason as better too.

Would you mind only fixing the typo?"

--> (To @collivier ) Please edit & commit change directly to this PR. Or, please provide exact line #(s) and verbiage to change(add)?"

**Comment by rabiabdel** [comment]
@collivier can you please check this PR

**Comment by collivier** [comment]
@rabi-abdel @rabiabdel I disagree with this PR (see comments) and I won't merge it. It would have been -2 in Gerrit. I'm playing for CNTT and then it's content quality.
Nothing forces me to accept all PRs proposed by others.

**Comment by rabiabdel** [comment]
@mf4716 is it OK to limit the PR to only fix the typos?

**Comment by mf4716** [comment]
Folks, these are minor changes, and supports Baldy deliverable, "baldy.rc1.1 | General Cleanup | All Chapters", by adding clarity to reasons for test scenario exclusion.  The same PR is leveraged to correct one/more section labels, and a typo in the chapter title.

For convenience, an explanation of the cosmetic changes can be found in the related issue #1162 .

Approvals would be appreciated to enhance the quality of the CNTT document for the end-user.

**Comment by mf4716** [comment]
Hi @deebhatia .  Yes, "If you agree, I will log a new issue. Not holding this one for that though.", I agree.  I did not change the reason's provided, only updated headers and lead-in sentences to offer clarity.  But, am in agreement that a qualifier could be used to denote "Optional" or "Known".  Thank you for reviewing.

**Comment by mf4716** [comment]
Any additional feedback, or can we approve?  Thanks

**Comment by pgoyal01** [comment]
@mf4716 
3.3.4.1. Identity - Keystone:: Keystone API v2 has been deprecated -- it is not allowed to be used because of security vulnerabilities. Tests should refer only to Keystone **API v3**; there should be no test cases or testing for Keystone API v2.

**Comment by pgoyal01** [comment]
@mf4716 
3.3.4.2 Image - Glance:: the Glance API to be used in v2 not v1 and hence the v1 test should not be included.

**Comment by pgoyal01** [comment]
@mf4716 
3.3.4.6 Compute - Nova:: Should the tests excluded because of "neutron" be part of the neutron test suite? nova-network is no longer an OpenStack service and hence any test cases belonging to nova-network should either be deleted or skipped. IMO, they should be marked as such not just "nova-network"

**Comment by mf4716** [comment]
Hi @pgoyal01 .  Appreciate the additional comments and rationale.  I was only making changes to the headers and a preceding statement before the tables.  Probably best to open a separate issue for changes to the reasons provided.  Thanks

**Comment by collivier** [comment]
@pgoyal01 @mf4716 nova-network is clear and explicit. tempest still support nova network testing which is out of scope CNTT (pike).
I do admit that I'm very surprised by the precisions asked here regarding the overall RC quality. I would strongly recommend we put effort on the parts which are in a bad shape.

**Comment by pgoyal01** [comment]
@collivier As you know, nova-network has been deprecated and so tests will always fail. Keystone API v2 has security vulnerabilities and has also been deprecated; dangerous to use.

Maybe tempest needs to be configured to disallow such testing.

**Comment by collivier** [comment]
@pgoyal01 yes that's why they are excluded. Everything is listed in RA1 chapter 5 and the test management in RC1 section introductions. Nothing wrong from a technical POV.

**Comment by mf4716** [comment]
Transitioning ownership to @prabhubalan (Prabhu Balan).  Would be my recommendation to discuss this PR during the next RIRC status call and attempt to reach consensus.  If consensus cannot be reached, it may be easier to cancel this PR and submit new/multiple PRs focused on very specific changes.

**Comment by fuqiao123** [comment]
@collivier according to your comments above, what is your suggestion for this PR. I think at least we can drop this one, and have another PR to only modify the typo?

**Comment by fuqiao123** [comment]
will close this one and @collivier will create a new one to cover the typo

**Pull request closed without merging**
