### PR TITLE
[RA1 README] Update schedule

### PR DESCRIPTION
**Pull request by pgoyal01**

### CODE REVIEW

**Review by collivier — CHANGES_REQUESTED** [review]
I would prefer us to remove this data which are not exported to GSMA.
As for ra1, we should rather consider a tag in git if needed.

**Comment by collivier** [comment]
@pgoyal01 another solution could be to leverage the only directive
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html

.. only:: html

**Comment by CsatariGergely** [comment]
> @pgoyal01 another solution could be to leverage the only directive
> https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html
> 
> .. only:: html

I would use this directive to maintain the consistency with the other documents.

**Comment by CsatariGergely** [comment]
I removed the version information and moved it to the root doc in #3077

**Comment by karinesevilla** [comment]
@CsatariGergely @collivier @pgoyal01 I am closing this PR, as a better solution was found. The releases history will be centralized for all documents

**Pull request closed without merging**
