### PR TITLE
Paris F2F Relese 1.0 Cleanup

### PR DESCRIPTION
**Pull request by rabi-abdel**
So far:

- incorporated @markshostak pull request https://github.com/cntt-n/CNTT/pull/100.
- Incorporated @ASawwaf Pull Request: https://github.com/cntt-n/CNTT/pull/74
- Incorporated @xavier-grall Pull Request: https://github.com/cntt-n/CNTT/pull/65
- Incorporated discussion between @bfcohen @xavier-grall @pgoyal01 about what goes into SW profile and what goes into HW Profile.
- Cosmetic Edits for all Chapters
- Added Release Information

### CODE REVIEW

**Comment by xavier-grall** [comment]
As requested by Rabi, our opinion (Karine and me, ie Orange) is that the following elements are not related to hw profile, but to sw profile or infra abstraction, and thus, they should not appear on that diagram (and even not in chapter 6):
- oversubscription level
- cpu pinning
- hugepages
The main rationale is that their management (activation, configuration, handling) requires at least an OS to be installed on the hw layer.
With the same rationale, DPDK and NIC bonding, which are also mentioned in chapter 6, are not elements of the hw profile either.

**Comment by rabi-abdel** [comment]
Hi @xavier-grall I agree. I will modify it accordingly today as part of the overall cleanup. Thanks

**Comment by pgoyal01** [comment]
Xavier and Karine,

They are not at the physical server level (CPU/BIOS) but the compute host information still needs to be configured in various systems prior for that compute host to be usable (available).

If we do not include that information then how can a request for a VM specified in the request with a sw flavour be resolved.

Best regards,
Pankaj
--------
pg683k@att.com | w  720.475.4530  |  m 720.327.0104

**Comment by xavier-grall** [comment]
Pankaj,
Of course, that information must be included to correctly instanciate a VM (especially for choosing the hosting compute node), and they are included in the configuration of NFVI software and/or VIM configurations, but not of NFVI  hardware (and thus, they are not related to chapter 6).

**Comment by xavier-grall** [comment]
> 
> 
> Pankaj,
> Of course, that information must be included to correctly instanciate a VM (especially for choosing the hosting compute node), and they are included in the configuration of NFVI software and/or VIM, but not of NFVI hardware (and thus, they are not related to chapter 6).

**Comment by bfcohen** [comment]
We do need to be careful about what is part of the HW layer and what is part of the SW layer.  Agree that what was called out is in fact part of the infrastructure software layer and as such should be moved.  However this does bring up an issue of where to put in BIOS, IPMI and other firmware settings that more directly interface with the actual hardware.  I would assume since those are typically supported by the HW vendors (Intel, Dell, etc.), these need to be in the HW section.

**Comment by rabiabdel** [comment]
@cntt-n great discussion everyone. i will try to incorporate those opinions for the discussion tomorrow.

**Comment by rabiabdel** [comment]
@ASawwaf, All can you check Chapter 2 modification and let me know if this looks good?

**Comment by xavier-grall** [comment]
@bfcohen 
I agree: in my opinion, the sw layer "begins" with host OS, while the hw layer "ends" with BIOS (so IPMI and other firmwares are in the hw layer)

**Comment by pgoyal01** [comment]
Ahmed,

Look good. In some places you have expanded the acronyms but not so in others. Also when you list component VNFs, is that comprehensive list.  You list HLR (which is 2G/3G) – should you instead refer to HSS?

Best regards,
Pankaj
--------
pg683k@att.com | w  720.475.4530  |  m 720.327.0104

**Comment by rabiabdel** [comment]
Really impressed with the quality of all Chapters :) Great work everyone @cntt-n. Talk to you tomorrow.

**Pull request merged**
