### PR TITLE
Chapter 01 (Terminology) 

### PR DESCRIPTION
**Pull request by karinesevilla**
Section 1.3:
addition to the definition of virtual storage resources
NFVi replaced by NFVI

### CODE REVIEW

**Comment by rabiabdel** [comment]
There is another existing pull request for terminology. A new consolidated pull request has been created: https://github.com/cntt-n/CNTT/pull/41

**Comment by rabiabdel** [comment]
Hi @karinesevilla this Pull request is created against the original text of terminology which has been proposed to change by @pgoyal01.
https://github.com/cntt-n/CNTT/pull/41 has been created to consolidate terminology edits suggestions. Can you have a look at it and let me know if you think your proposed  hanged here are reflected on the new consolidated terminology Pull request? In case you think so, we can close this Pull Request

**Comment by karinesevilla** [comment]
Yes this Pull Request can be closed

**Comment by rabiabdel** [comment]
Thank you @karinesevilla. Closing this Pull request as discussed.

**Pull request closed without merging**
