### PR TITLE
[RA-1 Ch02] Clean 2.3 -- "should" and "may" reqmts

### LINKED ISSUE #1618: [RA-1 Ch02] Move "should" and "may" requirements from 2.3 to 2.4
Section 2.3 should only contain "must" requirements but it still contains 10 "should" and 2 "may" requirements

Change has to be made in both Baldy and Baraque releases

### PR DESCRIPTION
**Pull request by pgoyal01**
Move "should" and "may" requirements from 2.3 to 2.4
This is for Baldy Release

Fixes #1618

### CODE REVIEW

**Comment by collivier** [comment]
@pgoyal01 We do cherry when the change in master is merged or at least well rated (else you would have to apply minor changes by hand instead of cherry-picking).
I fully agree that it has to be applied in Baldy.

**Comment by rabi-abdel** [comment]
@pgoyal01 can you please address @collivier & @karinesevilla comments above?

**Comment by rabi-abdel** [comment]
@pgoyal01 is this PR being discussed in RA-1 calls? will be good to get consensus on it.

**Comment by rabi-abdel** [comment]
@pgoyal01 I suggest closing this PR as we will do cherry pick later on. 

Rabi

**Comment by karinesevilla** [comment]
Approved per modifications merged on master

**Pull request merged**
