### PR TITLE
[RM Ch02 ] Profiles Image Update

### PR DESCRIPTION
**Pull request by xavier-grall**
Update the source image of chapter 02 profiles

### CODE REVIEW

**Comment by xavier-grall** [comment]
@ASawwaf 
This PR is only the update of the source image (pptx) of the image (png) which have already been updated by previous PR #

**Comment by xavier-grall** [comment]
@ASawwaf 
This PR is only the update of the source image (in the powerpoint file) of the image (in png format) which have already been approved by PR #329 
So, according to contribution process, I guess a new issue, followed by a new PR, should be proposed for that change.
But I agree that we could replace CDN by SGW, PGW or SPGW (rather than EPC, since it also includes MME which should be hosted by computing intensive profile).

**Comment by ASawwaf** [comment]
> @ASawwaf
> This PR is only the update of the source image (in the powerpoint file) of the image (in png format) which have already been approved by PR #329
> So, according to the contribution process, I guess a new issue, followed by a new PR, should be proposed for that change.
> But I agree that we could replace CDN by SGW, PGW or SPGW (rather than EPC, since it also includes MME which should be hosted by computing intensive profile).

Great  I will create new PR for this

**Comment by ASawwaf** [comment]
@xavier-grall ch02_infra_profiles image is not updated on the artefact , can you plz upload the updated version

**Comment by rabi-abdel** [comment]
Addressing https://github.com/cntt-n/CNTT/issues/357

**Pull request merged**
