### PR TITLE
JUN-1 TEST 2 TEST PR FOR JIRA GITHUB integration

### PR DESCRIPTION
**Pull request by jbeltranatl**
JUN-1 TEST Patch integration wJira

### CODE REVIEW

**Comment by rabi-abdel** [comment]
do you want to merge/approve  this @jbeltranatl or was that just a test?

**Comment by jbeltranatl** [comment]
it is a test only. but please approve.

**Comment by rabiabdel** [comment]
It requires 3 people approvals.

**Comment by jbeltranatl** [comment]
@mf4716 @rt063356 @rabi-abdel  Hi guys, this PR is linked to a JIRA issue thru a comment in the PR commit notes: https://jira.lfnetworking.org/browse/JUN-1. By by entering in the JIRA ID, "JUN-1" into the commit notes, JIRA automatically pulls it in via a plug-in that Jim Baker installed on the LFN JIRA instance. This is a test of the full cycle process of OPEN JIRA ISSUE>GITHUB PR PROCESS>CLOSE JIRA ISSUE. This tooling would eliminate the need to use GITHUB ISSUES and we could track all projects via JIRA--which will also link to other JIRA projects and integrate with Confluence. Again, this is a test. Please approve it.

**Comment by jbeltranatl** [comment]
@rabi-abdel Rabi, I also discovered that pretty much all work can be done from within the JIRA UI. If you could review the process and give feedback that would be helpful as we are running a 'bakeoff': Issues in JIRA vs. Issues in GitHub. Thx. 

FYI - @mtnskiier @walterkozlowski @mf4716 @rt063356

**Comment by jbeltranatl** [comment]
@mtnskiier you installed the BigBrassBand plug-in correct? But I think no changes were made to the GitHub side so I would think it'll synch the other way @mf4716. 

However, I did find this from GitHub itself which might could be used to synch the other way: https://github.com/integrations/jira

**Comment by jbeltranatl** [comment]
Question is whether two will conflict technically or functionally though.

**Comment by mf4716** [comment]
Thanks @jbeltranatl

**Comment by markshostak** [comment]
> 
> 
> @rabi-abdel Rabi, I also discovered that pretty much all work can be done from within the JIRA UI. If you could review the process and give feedback that would be helpful as we are running a 'bakeoff': Issues in JIRA vs. Issues in GitHub. Thx.
> 
> FYI - @mtnskiier @walterkozlowski @mf4716 @rt063356

Whoa. What exactly is the driver here? People are already having to learn 1 tool (github), do we really want everyone to have to learn and manage JIRA as well? Also, we're already split between github and confluence, and have to monitor both for actions. IMHO, **adding yet another platform to have to stay on top of in real-time, is a recipe for more things slipping through the cracks**, so there needs to be a strong reason to do it. Sorry to be a fire hose... -M

**Comment by rabiabdel** [comment]
Let's us discuss this more in details. Jira will be good to be used internally to track road map items and for nice reporting. I am not sure though the integration part to be honest :) it might just confuse everybody. But I am open offcourse to discuss it more and understand more the thinking behind this.

**Comment by mf4716** [comment]
OPNFV, Infra WG, and presumably others, use JIRA for support / lab mgmt.  Is it an inconvenience now to open JIRA tickets for lab support, then open a comparable GitHub issue to track CNTT work/metrics for the same task?  Not necessarily, just duplication of efforts.  Am I fan of leaning / using another tool?  No, unless it supports CNTT's Exit Strategy to LF/GSMA/OPNFV, and if it does, is now the right time to make this transition?  Probably not with everything else happening in parallel.

**Comment by markshostak** [comment]
> 
> 
> OPNFV, Infra WG, and presumably others, use JIRA for support / lab mgmt. Is it an inconvenience now to open JIRA tickets for lab support, then open a comparable GitHub issue to track CNTT work/metrics for the same task? 

Personally, I have no issue opening tickets in JIRA to action another group, such as the lab. In fact, it's great for that and I prefer it. I just don't want to have to monitor and manage yet another platform for the constant flow of CNTT document changes.

**Comment by walterkozlowski** [comment]
Hi All,
My 2 cents:


1.       I have partially participated in the bakeoff and I think there is a potential in the integration in the future.

2.       At this stage however we have to focus on the content creation. An introduction of any new tools and processes will delay such creation and, to be honest,  will in my view cause us missing the Snezka targets.

3.       I propose then:

a.       Do not make any changes before Snezka

b.      In the background continue testing tool and automation improvements keeping in mind that any future active use of Jira should be restricted  to  the core people (Leads and Co-leads) only, for the management purposes only, and NOT to be used by contributors, who should use GitHub for the content creation.  The contributors’ focus should always be the contents and never management.
Any thoughts?
Regards
Walter

**Comment by rabiabdel** [comment]
@walterkozlowski can't agree more! Could not have said it better.

**Comment by pgoyal01** [comment]
@walterkozlowski and @rabi-abdel If "future active use of Jira should be restricted  to  the core people (Leads and Co-leads) only, for the management purposes only" then seems to negate what is being proposed by @jbeltranatl "This tooling would eliminate the need to use GITHUB ISSUES and we could track all projects via JIRA--which will also link to other JIRA projects and integrate with Confluence. "

May I suggest that we clearly define the objectives for the use of JIRA and then the requirements (for example, bi-directional synch, etc.).

**Comment by walterkozlowski** [comment]
Hi Pankaj,
I totally agree we need to specify and agree on objectives and requirements. The overall goal is to automate our proceedings to make it easier for everybody (and definitely not more complex).  We are now in a discovery phase, I would say, hence the bakeoff  to find what technical capabilities are around.

I am not sure though my statement negates what we were together with Jonathan and Jim experimenting with.
 Jonathan talks about tracking issues within Jira, which is the management activity and hence should be managed by the Leads (as in my bullet points).
We all agreed that issues should be managed in one tool only and that Jira is a better positioned for this than GitHub. GitHub is a great tool for content management and hence should be the primary toolset for the contribution process (hence for the contributors). However, through integration Jira issues may be visible in GitHub (but we do not manage them there)

What I am advocating :

1.       Splitting issue management from the content creation.

2.       Automation of process through the tool integration.

3.       Not imposing for the whole community needs to work actively in two toolsets.  For clarity: it is not to introduce artificial limitations on people; just a separation of concerns and simplicity of operations (our own architectural principles after all…)


Clearly we all have to work on this more.
Cheers
Walter

**Comment by pgoyal01** [comment]
Walter,

Thanks. I will wait for the results of your exploration.

Please take into account that issues can be raised by non-leads but more important is the free flowing discussion that takes place once an issue is raised.

**Comment by walterkozlowski** [comment]
Pankaj,
Thanks.
As usual, your comments are very much to the point and helping to clarify somehow confusing  topics.

I have just realised that we are having an issue with the term issue (pun intended).  An issue in Jira is something very different from an issue in GitHub.  In Jira an issue can be one of the following: User Story, Task, Subtask, Bug.  While issues in GitHub should be used – as you are rightly emphasizing – to keep a content related discussion. And as such surely they should be created by anyone in the community who needs to raise something related to the contents they are contributing.  Currently though we are using GitHub issues both for this purpose and also for the  task management (GitHub issues like “create content for Chapter X” are actually tasks, and should not be confused with a content related issue like “this definition is incorrect because…”).  From the Governance perspective we as CNTT need to be able to measure progress and typically this is done by tracking progress in the task completion.  Jira is a good tool to do this, hence we are collectively thinking of using it for the TASK MANAGEMENT and PROGRESS REPORTING.  Currently this is done manually in Confluence using an arbitrary measure (“we think this is 50% complete”) or  by counting number of GitHub issues, which is misleading in view of the above (in a sense a big number of GitHub content related issues , not tasks, is a symptom of a good progress). To add to these complexities, we are trying to find an automated ways of connecting the ask completion progress in Jira with the progress of the actual GitHub content development. This is not that obvious. Hence the experiments and discussions.

I hope it clarifies a bit
Cheers
Walter

**Comment by pgoyal01** [comment]
Walter,
Thank you very much for pointing out the differences between JIRA and Github; my mistake should have read up on JIRA a little. It appears that we are headed to using JIRA Software projects rather than Business Projects. Is that because we expect to develop user "stories" at some point in time?

Would bugs be tracked in both JIRA and Github ("bug" label is used today)?

"From the Governance perspective we as CNTT need to be able to measure progress and typically this is done by tracking progress in the task completion." Will progress be measured in percentage or as a binary complete/non-complete. The former would require a finer granularity of work breakdown and time allocations. I would find it very difficult to predict completion rates, roadblocks and "bugs" as of now we have no history on our "team."

I suspect a number of folks are aligned with @markshostak (I know that I am) on the introduction of another tool in the mix.  Thus, from a naive perspective, if we need only to track "task complete/incomplete," would labeling a Github issue with "task", sub-task" etc. serve some of the objectives except for report automation? 

This doesn't require a response, something for you all to consider.

Thanks again.
Pankaj

**Comment by jbeltranatl** [comment]
4:38pm ET

**Pull request merged**
