### PR TITLE
[RM] Exceptions

### PR DESCRIPTION
**Pull request by rabi-abdel**
Fixes https://github.com/cntt-n/CNTT/issues/750

### CODE REVIEW

**Comment by pgoyal01** [comment]
@rabi-abdel I personally don't think that exceptions should be identified within RM or the RA's etc. I think there should be a separate consolidated document for both technology and version exceptions.

**Comment by ASawwaf** [comment]
@pgoyal01 @rabi-abdel , I am in favor off to have separate Annex, amendment collecting all expectation that we need to adopt during our roadmap as by time the exception should be resolved to avoid keep changes Rx

**Comment by rabiabdel** [comment]
@pgoyal01 @ASawwaf i would assume the opposite. if any exception is removed from any of the documents, that would be as a result of updating the document to support an alternative technology that gets rid off the exception so they will be updated together and stay on Sync. having those exception in the annex of RM (as to communicate this directly to VNF vendors) and in the annex of RA (as to communicate this directly to VI vendors) is the straight forward way of doing it.

**Comment by ASawwaf** [comment]
@rabi-abdel in both cases we will go to edit / remove it  :) 
lets see

**Pull request merged**
