### PR TITLE
[RC1][Ch03] Fixing typo

### LINKED ISSUE #1162: [RC1 - Ch03] Documentation Updates - Clarify Statements for Excluded Test Cases
Documentation clarification/updates needed:

1. Remove extra N in chapter title, "NNFVI Test Cases and Traceability to CNTT Requirements"

2. Expand, or clarify the statement, "test names must not be executed" for the following sections:
- 3.3.4.1 Identity - Keystone
- 3.3.4.2 Image - Glance
- 3.3.4.3 Block Storage - Cinder
- 3.3.4.4 Object Storage - Swift
- 3.3.4.5 Networking - Neutron
- 3.3.4.6 Compute - Nova

**Change** "According to [RA1 Core OpenStack Services APIs]({{ "/doc/ref_arch/openstack/chapters/chapter05.html" | relative_url }}) the following test names must not be executed:" 

**To** According to [RA1 Core OpenStack Services APIs]({{ "/doc/ref_arch/openstack/chapters/chapter05.html" | relative_url }}) the following tests will be excluded as there is no corresponding mandatory requirement for the feature/capability in RA-1, or there is a known issue with the feature/capability prohibiting execution:

3. Repeat sections in 2, and update the subsequent column headers with more clarity re: Exclusion, and Reason.
a) change "test rejection regular expressions" to "Excluded Test (expression reference)"
b) change "reason" to "Optional in RA-1 requirement, or Known Issue"

### PR DESCRIPTION
**Pull request by prabhubalan**
Fixes #1162

### CODE REVIEW

**Comment by collivier** [comment]
NFVI must be changed to Cloud Infrastructure

**Comment by prabhubalan** [comment]
> NFVI must be changed to Cloud Infrastructure

I thought so @collivier  as per the recent communication.

**Comment by collivier** [comment]
@prabhubalan Thank you

**Comment by pgoyal01** [comment]
NFVI occurs in RC-1 CH03 in multiple places:
3.1 Introduction -- twice
3.3 Traceability Matrix --- multiple times
5.3.6 (3.3.6) Dataplane benchmarking -- once
3.4.1 RM/RA-1 Requirements -- once

Other Typos:
TOC lists 3.3 as Test Cases but with in text as Traceability Matrix
5.3.6 Dataplane benchmarking --> should be 3.3.6
Some of the references to other CNTT content are relative while others are absolute -- should be relative.

**Comment by pgoyal01** [comment]
Sorry for accidental closure

**Comment by prabhubalan** [comment]
> Sorry for accidental closure

no problem @pgoyal01

**Comment by prabhubalan** [comment]
> NFVI occurs in RC-1 CH03 in multiple places:
> 3.1 Introduction -- twice
> 3.3 Traceability Matrix --- multiple times
> 5.3.6 (3.3.6) Dataplane benchmarking -- once
> 3.4.1 RM/RA-1 Requirements -- once
> 
> Other Typos:
> TOC lists 3.3 as Test Cases but with in text as Traceability Matrix
> 5.3.6 Dataplane benchmarking --> should be 3.3.6
> Some of the references to other CNTT content are relative while others are absolute -- should be relative.

Thanks @pgoyal01. This PR is to fix #1162. I have fixed other typos as you pointed. This PR is not to replace the NFVI. This needs to be discussed in the RC call.

**Comment by rabi-abdel** [comment]
@pgoyal01 can you please approve

**Pull request merged**
