### PR TITLE
[Edge] Adding Files (Figures) for Edge Use Cases 

### PR DESCRIPTION
**Pull request by Karimrabie**
This is to upload the Figures used for the Edge use cases.

### CODE REVIEW

**Comment by pgoyal01** [comment]
@Karimrabie Since a review has been requested -- please remove WIP

**Comment by Karimrabie** [comment]
> @Karimrabie Since a review has been requested -- please remove WIP

Done

**Comment by pgoyal01** [comment]
@Karimrabie The figures need to be named as per the rules; WS-Chapter-Descriptive-Title

**Comment by Karimrabie** [comment]
> @Karimrabie The figures need to be named as per the rules; WS-Chapter-Descriptive-Title

@pgoyal01 Currently it is Edge_UsecaseX_Title (Edge_Usecase1_CDN)
What do you suggest as a name?

**Comment by pgoyal01** [comment]
@Karimrabie Are the Edge Use cases targeted for the Reference Model (RM) Chapter 05? If yes, then RM-Ch05-<Title> -- the image file (png) would ahve the extension .png while the corresponding source file will have .pptx

**Pull request closed without merging**
