### PR TITLE
[RA-1 All] Introduce OpenStack "server" concept

### LINKED ISSUE #2497: [RA1 Ch-All] Standardise on use of the term "server"
Standardise on use of the term "server" for physical, VM or container

### PR DESCRIPTION
**Pull request by pgoyal01**
Fixes #2497 

Changes to common/glossary; and RA-1 chapters

Delete bogometers

use of the terms _instances_ and _servers_ as appropriate

### CODE REVIEW

**Comment by pgoyal01** [comment]
@cntt-n/ref-a1 Can folks please review and approve -- it is a set of simple changes? Tomorrow November 2nd is the last day for the M3 milestone. Thanks.

**Review by ildikov — APPROVED** [review]

**Review by gkunz — APPROVED** [review]

**Comment by gkunz** [comment]
@pgoyal01 is the intention to remove the bogometers globally or just for the mature workstreams such as RA1? I am fine either way and merely wondering if I missed a discussion on this topic.

**Comment by pgoyal01** [comment]
> @pgoyal01 is the intention to remove the bogometers globally or just for the mature workstreams such as RA1? I am fine either way and merely wondering if I missed a discussion on this topic.

@gkunz I think the agreement was to remove them globally.

**Comment by gkunz** [comment]
> @gkunz I think the agreement was to remove them globally.

ok, thanks. I have a PR which adds missing bogometers to RC2 (in addition to proofreading fixes). So, I might want to rather remove the bogometers in RC2. However, RC2 is much less mature than RA1 and most chapters are in "SME feedback" and "initial framework" state and the bogometers can highlight this to "external readers".

**Pull request merged**
