### PR TITLE
[TSC] - Delete Hallasan.md #1409

### LINKED ISSUE #1409: [Tech Release notes] Delete Hallasan
https://github.com/cntt-n/CNTT/tree/prabhubalan-patch-1/doc/tech/release_notes

Please delete Hallasan Release

### PR DESCRIPTION
**Pull request by prabhubalan**
Removing the Hallasan references as this release is descoped

Fixes #1409

### CODE REVIEW

**Comment by tomkivlin** [comment]
Assume you've checked if there are any links incoming to this page?

**Comment by prabhubalan** [comment]
> Assume you've checked if there are any links incoming to this page?

@tomkivlin - Yes, there is no link associated for this Hallasan.md.

**Comment by pgoyal01** [comment]
@prabhubalan Deletion of Hallasan requires adjustments to the Baraque release.

<p align="center">Baldy Release Organisation</p>
<p align="center"><b>Figure 1:</b> Baldy Release Organisation</p>


<p align="center">Baraque Release Organisation</p>
<p align="center"><b>Figure 1:</b> Baraque Release Organisation</p>

When you delve deeper into the release contents the issue becomes clearer. For example,

## Reference Model (v3.0) (Baldy Release)
Reference # | Feature | Notes
-- | -- | --
baldy.rm.1 | General Cleanup | All Chapters
baldy.rm.2 | Limiting infrastructure profiles to Basic and Network Intensive (Parking Compute intensive) | Ch02, Ch04, and Ch05
baldy.rm.3 | Finalising Compliance, Verification and Conformance Strategy | Ch08
baldy.rm.4* | Full Container support | Ch04
baldy.rm.5 | Complete Security Chapter | Ch07: 100% alignment with ONAP
baldy.rm.6 | Virtual Networking/ Networking Fabric Modelling | Ch03
baldy.rm.7 | Generic Installer Model | Ch09
baldy.rm.8 | Guidelines | Appnedix-A


## Reference Model (v3.x) (Baraque release)
Reference # | Feature | Notes
-- | -- | --
baraque.rm.1 | TBD |  
baraque.rm.2 | TBD |  
baraque.rm.3 | TBD |  
baraque.rm.4* | TBD |  
baraque.rm.5 | TBD |  
baraque.rm.6 | TBD |  
baraque.rm.7 | TBD |  
baraque.rm.8 | TBD |  

Both the Baldy and Baraque releases only cover the first 4 chapters of RM. There are similar issues with the other WSs.

FYI: For RA-1, except for the Security Chapter 6, we will have completed all chapters in the Baldy release; we will try very hard to even complete Chapter 6 given the extra time.

**Comment by rabi-abdel** [comment]
> @prabhubalan Deletion of Hallasan requires adjustments to the Baraque release.
> 
> Baldy Release Organisation
> 
> Figure 1: Baldy Release Organisation
> 
> Baraque Release Organisation
> 
> Figure 1: Baraque Release Organisation
> 
> When you delve deeper into the release contents the issue becomes clearer. For example,
> 
> ## Reference Model (v3.0) (Baldy Release)
> Reference #	Feature	Notes
> baldy.rm.1	General Cleanup	All Chapters
> baldy.rm.2	Limiting infrastructure profiles to Basic and Network Intensive (Parking Compute intensive)	Ch02, Ch04, and Ch05
> baldy.rm.3	Finalising Compliance, Verification and Conformance Strategy	Ch08
> baldy.rm.4*	Full Container support	Ch04
> baldy.rm.5	Complete Security Chapter	Ch07: 100% alignment with ONAP
> baldy.rm.6	Virtual Networking/ Networking Fabric Modelling	Ch03
> baldy.rm.7	Generic Installer Model	Ch09
> baldy.rm.8	Guidelines	Appnedix-A
> ## Reference Model (v3.x) (Baraque release)
> Reference #	Feature	Notes
> baraque.rm.1	TBD	 
> baraque.rm.2	TBD	 
> baraque.rm.3	TBD	 
> baraque.rm.4*	TBD	 
> baraque.rm.5	TBD	 
> baraque.rm.6	TBD	 
> baraque.rm.7	TBD	 
> baraque.rm.8	TBD	 
> Both the Baldy and Baraque releases only cover the first 4 chapters of RM. There are similar issues with the other WSs.
> 
> FYI: For RA-1, except for the Security Chapter 6, we will have completed all chapters in the Baldy release; we will try very hard to even complete Chapter 6 given the extra time.

@pgoyal01 the scope of Baraque might be adjusted slightly and this is something we started to do in our TSC planning and we will take into account. this PR should not be impacted as there will be new PR for the roadmap for Baraque once it is all understood.

**Comment by pgoyal01** [comment]
@rabi-abdel Given the Baldy release it would appear that Baraque would have to radically adjusted. Given that changes will be made in another PR -- I will approve.

**Pull request merged**
