### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by tomkivlin**
Propose adding a licence (I am proposing the simple MIT licence) even if we're going to move to GSMA/LFN tools / licences at some point.

### CODE REVIEW

**Comment by markshostak** [comment]
Hi Tom, Good catch! There definitely has to be a license (IMHO), but which license to adopt is a governance problem. I'd suggest you open an issue (so we don't forget about it), then kick it over to them. -M

**Comment by tomkivlin** [comment]
OK, yes that makes sense - who is "them"?

**Comment by tomkivlin** [comment]
@markshostak done!  See issue #77. 
I've also raised issues for code of conduct (#78) and contribution guidelines (#79)

**Comment by markshostak** [comment]
Hmm, hopefully those other 2 issues weren't related to my comment! :-)
But kidding aside, by "them" I was referring to the Governance team (the Thursday mtg team (David, Heather, etc.)). -M

**Comment by tomkivlin** [comment]
Ah OK fab thanks.

**Comment by rabiabdel** [comment]
Deferred to governance team, close for now

**Pull request closed without merging**
