### PR TITLE
Position CNFs as Release 2 roadmap item

### PR DESCRIPTION
**Pull request by BernardTsai-DT**
Referring to #203, #198

Describes in section 1.9 how Releases 1 and 2 of the Reference Model will address VNFs and CNFs.

### CODE REVIEW

**Comment by rabi-abdel** [comment]
We need a roadmap diagram to compliment this sentence.

**Comment by karinesevilla** [comment]
I thought that the reference model will stay agnostic to VM and containers

**Comment by BernardTsai-DT** [comment]
The reference model should be agnostic but possibly certain aspects of the model might have to be readjusted due to additional aspects which may become of relevance when analysing CNF workloads.

**Comment by rabiabdel** [comment]
Defer to future if needed.

**Pull request closed without merging**
