### PR TITLE
[RA2] relative links

### LINKED ISSUE #2361: [doc] Change internal links to relative links
All internal links to Anuket specifications should be relative links instead of absolulte ones. Using absolulte links points to wrong targets in case of using multiple branches.

### PR DESCRIPTION
**Pull request by EditKoselak**
Partially fixes #2361

### CODE REVIEW

**Review by rgstori — APPROVED** [review]

**Review by walterkozlowski — APPROVED** [review]

**Comment by pgoyal01** [comment]
There is an unresolved conflict

**Review by pgoyal01 — APPROVED** [review]
subject to conflict resolution

**Review by tomkivlin — APPROVED** [review]

**Review by gkunz — APPROVED** [review]

**Comment by wmk-admin** [comment]
@rgstori: Can you please remove conflicts so I could merge this PR? Thanks. Walter

**Comment by wmk-admin** [comment]
@pgoyal01 can you perhaps help @rgstori to remove the conflicts, so we could merge?

**Comment by pgoyal01** [comment]
@EditKoselak can you please resolve the conflicts -- I cannot access the conflicting file to see where the conflict is. @CsatariGergely Can you please help? Thanks

**Pull request merged**
