### PR TITLE
Post Paris Cleanup

### PR DESCRIPTION
**Pull request by rabi-abdel**

### CODE REVIEW

**Comment by rabi-abdel** [comment]
> Should Chapter 4 be labeled "NFVI Capabilities and Catalogue" as "Infrastructure Abstraction" is too generic for the very specific content of this Chapter.

good point. will rename

**Comment by samuelhellec** [comment]
@rabi-abdel 

In the merge of chapter 5 & 6 it looks like we lost the previous content of chapter 5.

The strange things is that I do not see it in the changes as removed.

Did you do some commits before that would have removed it?

**Comment by rabi-abdel** [comment]
> @rabi-abdel
> 
> In the merge of chapter 5 & 6 it looks like we lost the previous content of chapter 5.
> 
> The strange things is that I do not see it in the changes as removed.
> 
> Did you do some commits before that would have removed it?

@samuelhellec can you please check this file: https://github.com/cntt-n/CNTT/blob/rabi-abdel-patch-1/doc/ref_model/chapters/chapter05.md

do you still something missing?

**Comment by samuelhellec** [comment]
> > @rabi-abdel
> > In the merge of chapter 5 & 6 it looks like we lost the previous content of chapter 5.
> > The strange things is that I do not see it in the changes as removed.
> > Did you do some commits before that would have removed it?
> 
> @samuelhellec can you please check this file: https://github.com/cntt-n/CNTT/blob/rabi-abdel-patch-1/doc/ref_model/chapters/chapter05.md
> 
> do you still something missing?

@rabi-abdel 
Thanks Rabi It is ok now

**Pull request merged**
