### PR TITLE
[RA2 Core]: ToC proposal for Ch3 and Ch4

### PR DESCRIPTION
**Pull request by CsatariGergely**
This change contains an open ended proposal for the structure of
Ch3 and Ch4.

### CODE REVIEW

**Comment by CsatariGergely** [comment]
Fixes #457

**Comment by pgoyal01** [comment]
@CsatariGergely Where would you discuss the  physical resources and k8s cluster considerations?

**Comment by CsatariGergely** [comment]
> 
> 
> @CsatariGergely Where would you discuss the physical resources and k8s cluster considerations?

In Chapter 2 we should sort out the exact requirements of these. I saw lots of cluster LCM requirements in #445  but as I remember we agreed in Antwerp not to include these into the RA and we should focus on the interface towards the VNF. 

If we need to sort these out I would put generic subchapters to Chapter 3 to discuss the base of the component selection and subchapters to Chapter 4 for the component selections.

**Comment by tomkivlin** [comment]
Should we have a 3.4 Container Storage Services, to capture the architecture of the storage that might be provided from an NFVI to a CaaS/CNF?

**Pull request merged**
