### PR TITLE
RA2 ch2 - align with RM security requirements

### LINKED ISSUE #2009: [RA2 Ch2] Update security requirements from RM
Changes to RM took place in #2002 and will need reflecting in RA2.

### PR DESCRIPTION
**Pull request by tomkivlin**
Resolves #2009

### CODE REVIEW

**Review by pgoyal01 — APPROVED** [review]

**Review by ulikleber — APPROVED** [review]

**Review by deebhatia — APPROVED** [review]

**Review by petorre — APPROVED** [review]

**Review by rgstori — APPROVED** [review]

**Comment by tomkivlin** [comment]
Note - @karinesevilla will add further updates to align with changes in RM since #2009 was logged.  Please don't merge yet.

**Comment by tomkivlin** [comment]
@karinesevilla are we good to merge this now? Thanks for the updates.

**Comment by karinesevilla** [comment]
@tomkivlin Ok done, good to merge

**Comment by tomkivlin** [comment]
> @tomkivlin Ok done, good to merge

Many thanks!

**Pull request merged**
