### PR TITLE
[RA1][RC1]List Network Type drivers in RA1 Chapter5

### PR DESCRIPTION
**Pull request by collivier**
It sets vlan as mandatory and all L3 overlays as optional.
One of them must be implemented in case of L3 network fabric.

It updates both RA1 and RC1 according to the traceability in place.
It's being completed by the regex update in Functest.

Fixes: #1077

Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>

### CODE REVIEW

**Comment by rabiabdel** [comment]
@collivier i moved your changes on Ch05 to Ch03, let me know if i missed it up!

**Comment by rabiabdel** [comment]
@mf4716 @pgoyal01 please review/approve

**Comment by collivier** [comment]
@rabiabdel It seems you didn't adapt the tab size as I did. Else the results seem good even I'm lost in github commits (normally we shouldn't add merge commits)

**Comment by rabiabdel** [comment]
> @rabiabdel It seems you didn't adapt the tab size as I did. Else the results seem good even I'm lost in github commits (normally we shouldn't add merge commits)

i don't know how the rebase work! but i see your point.

**Pull request merged**
