### PR TITLE
Update chapter10.md

### PR DESCRIPTION
**Pull request by rabiabdel**
Adding proposed outline for Chapter 10.

### CODE REVIEW

**Comment by cntt-n** [comment]
Add more entries to outline

**Comment by rabiabdel** [comment]
Ok Change made

**Comment by rabiabdel** [comment]
@ Pankaj, please add your comment to this Commit in here.

**Comment by pgoyal01** [comment]
Unable to edit the "pull".
I think the Chapter is about Compliance, Verification and Certification (CVC) and thus needs to focus on the CVC Lifecycle including processes and tools – model level. The CVC services shall be performed on CNTT specified Reference Implementations – but these reference implementations are not yet specified.  It appears to me that the best plan would be to modify the OPNFV CVC processes (diagrams) to refer to CNTT NFVi Reference Implementation wherever they have NFVi etc. Do you agree? If yes, then the chapter content could be as follows:
 
#  Compliance, Verification and Certification (CVC)
[10.1  Introduction]
[10.2  Compliance process adapted from OPNFV (specifies the process with changes)]
[10.4  Verification (rest same as above)]
[10.4  Certification (rest same as .1)]
[10.5  Comparison chart of CVC and recommendation for NFVi and C/VNF’s]

**Comment by cntt-n** [comment]
Hi @pgoyal01 i have made changes to reflect your feedback, is the change aligned with your expectation?

**Comment by rabiabdel** [comment]
Hi @pgoyal01 i have made changes to reflect your feedback, is the change aligned with your expectation?

**Pull request merged**
