### PR TITLE
[RI2] Wrapping all lines to 120 chars and enforcing checks

### PR DESCRIPTION
**Pull request by gkunz**
This PR wraps the last remaining lines (requirements table in ch02)
to 120 characters. It also enforces checking of the 120 character
line length limit at build time.

Signed-off-by: Georg Kunz <georg.kunz@ericsson.com>

### CODE REVIEW

**Comment by gkunz** [comment]
Hi @collivier, @xudan16 can you please review? Thanks a lot!

**Review by walterkozlowski — APPROVED** [review]

**Comment by xudan16** [comment]
Hi @gkunz , the cntt-tox and cntt-tox-rc1 jobs are both failed, but cannot open the link to get the details. Could you check that?

**Comment by gkunz** [comment]
Hi @xudan16. Yes, the infra running the checks are broken. @collivier is waiting for LF to fix the build server. In the meantime, we have to resort to manual verification, unfortunately.

**Review by xudan16 — APPROVED** [review]

**Review by collivier — APPROVED** [review]
You may take into account that wrapping to 120 can easily fail when generating PDF.

**Pull request merged**
