### PR TITLE
Chapter06 (cleanup)

### PR DESCRIPTION
**Pull request by pgoyal01**
Made changes to the Text. Other changes to follow once can get the new figure uploaded.

### CODE REVIEW

**Comment by karinesevilla** [comment]
@pgoyal01 
Hi Pankaj
The image corresponding to figure 6.1 is wrong, it's SW profile and not HW.

chap6_figure6_1_Hw_profile

**Comment by karinesevilla** [comment]
It should be the image sent with my previous comment

**Comment by rabiabdel** [comment]
@pgoyal01 Please fix as per @karinesevilla comment.

**Comment by BernardTsai-DT** [comment]
In the diagram doc/ref_model/figures/Chapter-6-HW-SW-Profile-Diagram.png it would be great if we would not only refer to compute but also to network and storage resources. So would it be possible to have as a caption in the orange box: Virtual Infrastructure Resource

**Comment by pgoyal01** [comment]
My original diagram had VIR but someone didn’t like that. Will change. Thanks

Best regards,
Pankaj
--------
pg683k@att.com | w  720.475.4530  |  m 720.327.0104

**Comment by pgoyal01** [comment]
Bernard,
Incorporated your request.

**Comment by rabiabdel** [comment]
Update diagram as per discussion

**Comment by rabiabdel** [comment]
@pgoyal01: let me know once you done with this Pull Request, i will merge once you ready. i am assuming you and @karinesevilla agreed on this diagram, right?

**Comment by pgoyal01** [comment]
Rabi,
Had a number of exchanges primarily with Xavier on Friday. I think, at a minimum, Karine and Xavier should review both the diagram and the content changes; other should too but Xavier had important insights.

**Comment by rabiabdel** [comment]
@karinesevilla @xavier-grall can you both please review this and let me know if you are happy with it? we need to get this done ASAP. Thanks

**Comment by rabiabdel** [comment]
for sake of time, i will approve it and merge it. in case any more changes needed by @karinesevilla @xavier-grall, we can reflect them in the release cleanup Pull Request https://github.com/cntt-n/CNTT/pull/101

**Pull request merged**
