### PR TITLE
[RC1 - Ch1.8] Add Results Collation Process

### LINKED ISSUE #1258: [RC1 - Ch1.8] baldy.rc1.1:  Add Results Collation Process
Supports: baldy.rc1.1 General Cleanup

Purpose: Conduct discussions & document outcome in RC1 Ch1.8 ("Results Collation & Presentation") for establishing a common repo for test results collation and results presentation which:

- supports a badging program
-  enables CNTT RIRC deliveries for Baldy
- serves as a common results platform for OPNFV test projects & the friendly RI-1 trial partners

Update TOC to align with document sections.

### PR DESCRIPTION
**Pull request by mf4716**
Fixes #1258 

[RC1 - Ch1.8] baldy.rc1.1: Add Results Collation Process

Fix TOC to match sections.

### CODE REVIEW

**Comment by mf4716** [comment]
TOC corrected 3/5.  1.8 content to be written upon clarification of process and tools.  Initial meeting 3/5.  Work in progress.  Follow-up scheduled 3/16.

**Comment by mf4716** [comment]
Transitioned ownership to @prabhubalan (Prabhu Balan).  

Adding Reviewers from the initial conversation to assist Prabhu with current status on Next Steps as outlined in the related issue #1258 .  Repeated here for convenience:

**Next steps**
o Cedric to make initial relative path change. Team will monitor/review via Gerrit.
o Lincoln & Kanag to perform a deeper dive into the Functest output to identify any other changes possibly needed on the Portal side, or Functest side.
o Team agreed to work issues via offline means (email, Gerrit, etc).

**Comment by fuqiao123** [comment]
I think I am OK with this one, just minor modification. I will wait and see if we have further comments for this. If not, I am OK to merge it.

**Comment by fuqiao123** [comment]
@collivier @rabi-abdel please see if you are OK with this one. If so, we can merge this one on today's RC call.

**Comment by fuqiao123** [comment]
will create a new PR and close this one

**Pull request closed without merging**
