### PR TITLE
[RM Ch04] Fix Profile Capability mapping

### LINKED ISSUE #1748: [RM Ch04] Fix 4.2.5 Profile Capability Mapping
Possibly remove it as there is similar chapter in Ch05

### PR DESCRIPTION
**Pull request by karinesevilla**
fixes #1748 
4.2.5
SR-IOV over PCI-PT: No for Basic Profile , Yes for Network intensive profile

### CODE REVIEW

**Comment by ASawwaf** [comment]
@karinesevilla  , We need to add Note above the SRIOV as a transition technology as it covers under CNTT as transition

**Comment by rabi-abdel** [comment]
hi @karinesevilla do you mind resolving the conflict above?

**Comment by karinesevilla** [comment]
@ASawwaf Yes you're right. I added a note for SR-IOV.

**Comment by ASawwaf** [comment]
Thanks @karinesevilla

**Pull request merged**
