### PR TITLE
[RA1, Common] Architectural Principles

### LINKED ISSUE #3145: [common Ch00] Architectural principles
what does the following say:
1. Open source preference: To ensure, by building on technology available in open source projects, that suppliers’ and operators’ investment have a tangible pathway towards a standard and production ready Cloud Infrastructure solution portfolio.

I think there are grammatical issues, and there are unjustified implications. For example, how does using open-source technology create a "tangible pathway" for investments?

There are grammatical issues, in my opinion, with the other principles also.

### PR DESCRIPTION
**Pull request by karinesevilla**
Wording
Fixes #3145

### CODE REVIEW

**Review by pgoyal01 — APPROVED** [review]

**Comment by pgoyal01** [comment]
Since this PR affects "common", it would be nice to get approvals from at least a majority of the WS Leads, and the two TSC Leads before merging.

**Review by collivier — APPROVED** [review]

**Review by steelescotr — APPROVED** [review]

**Comment by collivier** [comment]
We should have split into 2 commits if the common part is waiting for one approval per WS.
The RA1 part needs a quick merge (GSMA).

If it's a majority - we already got it here

**Comment by collivier** [comment]
I'm wondering how this change would be applied in RM as far as I remember this part is manually edited and unsynced between RM and the GSMA docs.

**Comment by karinesevilla** [comment]
@walterkozlowski @rgstori @bfcohen @CsatariGergely Can you please review?

**Comment by collivier** [comment]
@walterkozlowski @rgstori @bfcohen @CsatariGergely I will merge it end of day. RA1 needs this change for GSMA and this PR reaches the criteria.

It must be noted that RA1 is fully automated and we don't want to diverge between GSMA and Anuket RA1.

**Review by CsatariGergely — APPROVED** [review]

**Review by walterkozlowski — APPROVED** [review]

**Comment by collivier** [comment]
thank you @walterkozlowski for the merge

**Pull request merged**
