### PR TITLE
Chapter08

### PR DESCRIPTION
**Pull request by kagreenwell**
Original commit for CH8 content.

### CODE REVIEW

**Comment by mf4716** [comment]
Reviewed.  A few image files (4) did not appear to be part of the PR.  We will review the merge after and confirm which files are missing, if any.  Approved.

**Comment by rabi-abdel** [comment]
@mf4716 I think you have closed it by mistake. you need to click "Add your review" in the top and approve it. then we approve it during tomorrow's meeting and merge it.

**Comment by rabi-abdel** [comment]
@mf4716 Thanks for the changes as requested. if no comments or objections to approve it, i will go ahead and approve it within 48 working hours). 
All: please review and provide input.

**Comment by rabiabdel** [comment]
Although I believe more cleanup is still needed and to remove of duplicates, i will merge it for now as to have the initial content in. i will create an issue to track cleaning up the content.

**Comment by rabiabdel** [comment]
48 hour pass, so approve and merge

**Pull request merged**
