### PR TITLE
Updated Chapter08.MD with all the comments and changes

### PR DESCRIPTION
**Pull request by bfcohen**
Could not figure out how to do it from my branch, so did it from the master.

### CODE REVIEW

**Comment by bfcohen** [comment]
Folks -
Incorporated the comments and new materials from several contributors.

**Comment by rabi-abdel** [comment]
Thanks @bfcohen looks really good.
Rabi

**Comment by rabiabdel** [comment]
@bfcohen this is great work :) Thanks!

**Comment by rabiabdel** [comment]
Really impressed with the quality of all Chapters :) Great work everyone @cntt-n. Talk to you tomorrow.

**Pull request merged**
