### PR TITLE
[RC1] Remove falsy duplicated req tabs

### PR DESCRIPTION
**Pull request by collivier**
They are outdated and then falsy duplicate RM and RA tabs.

Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>

### CODE REVIEW

**Comment by collivier** [comment]
As discussed in RA1 meetings.

**Comment by pgoyal01** [comment]
Cedric, Need @rabi-abdel and @fuqiao123 to weigh in. I agree that these requirements are obsolete as they are not aligned with the RA-1 requirements (some are and some are not).

The question is should RC duplicate the RA-1 requirements? If yes, we will need to copy the requirements from RA-1 Ch02 as I don't know of any way in md to reproduce content by reference.

**Comment by fuqiao1** [comment]
> Cedric, Need @rabi-abdel and @fuqiao123 to weigh in. I agree that these requirements are obsolete as they are not aligned with the RA-1 requirements (some are and some are not).
> 
> The question is should RC duplicate the RA-1 requirements? If yes, we will need to copy the requirements from RA-1 Ch02 as I don't know of any way in md to reproduce content by reference.

I understand the table are not correct with the current RA-1 is because these tables copied RI-1 chp3, and those tables in RI-1 were writen months ago and were basicaly copy content in RA-1 back at that time. I don't think it make sense actually for RI and RC to copy these tables and make it difficult to manage these tables in different WS. In the meantime, these tables can hardly translate in to real test cases. If the TSC care about tracebility of RA requirement in RC, I think it is important that tables in RA translate into exact cases/requirement bullets for RC to check.

**Comment by rabi-abdel** [comment]
@fuqiao1 @collivier @pgoyal01 let us discuss this quickly in the TSC call today.

**Comment by collivier** [comment]
Here we should follow the code development principles.
When code is copied/pasted, we do factorize. When the duplicated code is even falsy, it's become a key issue. Here it should be noted that RC isn't the right source (it's RM and RA).

**Comment by rabi-abdel** [comment]
@rabi-abdel to work with Cedric and fu Qiao to finalise this

**Comment by collivier** [comment]
@rabi-abdel @fuqiao123 @fuqiao1 As discussed in TSC: They are false. They must be removed first and then enhanced. We can't block this PR till the upcoming release.

**Comment by rabi-abdel** [comment]
@collivier I commented them out rather than removing them completely! will merge by end of day. let me know what you think before then,

**Comment by collivier** [comment]
@rabi-abdel I fully disagree to only comment the tabs here because it doesn't fix the bugs.
I don't see why we selected a disruptive approach (they are now still in md files) without CNTT RC lead and Co-lead asking for it and this way hasn't been discussed in TSC. I would appreciate quick clarifications about the role of CNTT RC lead/co-lead.

**Comment by collivier** [comment]
@rabi-abdel In fact it's even worse as it refers to Functest without any Functest contributor involved.
Commenting this tab doesn't fix the bug and more important doesn't match CNTT role and OPNFV meritocraty. No CNTT role allows speaking on behalf of Functest without contributing.

**Pull request merged**
