### PR TITLE
[RA-1 Ch06] Replaced HTML lists with Markdown

### LINKED ISSUE #1554: [RA1 Ch06] Fix formatting and clean up HTML code
Change any HTML to Markdown and clean up the table formats

### PR DESCRIPTION
**Pull request by yeelinglam**
Fixed #1554 
Also fixed table format, but left the img and heading ID along as MD didn't work properly for them.

### CODE REVIEW

**Comment by pgoyal01** [comment]
@yeelinglam: Section 6.3.1.2, the *Special Note on logging Tenants* under "Keystone Token" has HTML for bold and italic.

**Comment by pgoyal01** [comment]
@rabi-abdel These are format changes -- can they be merged as part of the Baldy proof reading exercise?

**Comment by yeelinglam** [comment]
@pgoyal01 thank you for catching that, fixed!

**Comment by rabi-abdel** [comment]
> @rabi-abdel These are format changes -- can they be merged as part of the Baldy proof reading exercise?

Yes.

**Comment by pgoyal01** [comment]
@rabi-abdel Thanks. I have reviewed and approved -- only html to md changes.

**Comment by pgoyal01** [comment]
@iangardner22 @karinesevilla Can you please review and approve? Thanks. Only html changes

**Pull request merged**
