### PR TITLE
[RA2 Ch1] Updated Figure 1-1

### LINKED ISSUE #2248: [RA2 Ch01] Figure 1-1 -- replace NFVI
Figure 1-1 -- replace NFVI with Cloud infrastructure in the "Physical/virtual compute, storage ..." box

### PR DESCRIPTION
**Pull request by petorre**
As per RM Ch3 changed: NFVI -> HW Resources, VIM -> HW Infra Mgr. Also changed: Master -> Control.
Fixes #2248

### CODE REVIEW

**Comment by pgoyal01** [comment]
@petorre Does the "Master" in "Kubernetes Master Machine (Virtual / Physical)" -- it is just below the text you changed to "Kubernetes Control OS" -- also need to changed to "Control"; should we also change "Machine" to "Node" or "Host", ....?

**Comment by petorre** [comment]
@pgoyal01 : Yes. Please see now.

**Review by pgoyal01 — APPROVED** [review]

**Review by CsatariGergely — CHANGES_REQUESTED** [review]
Please provide also the editable variant also of the file.

**Comment by rgstori** [comment]
> Please provide also the editable variant also of the file.

@tomkivlin do you happen to know where is the source pptx for this please?

**Review by rgstori — APPROVED** [review]

**Comment by tomkivlin** [comment]
> > Please provide also the editable variant also of the file.
> 
> @tomkivlin do you happen to know where is the source pptx for this please?

In the /figures directory: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/figures/k8s-ref-arch-figures.pptx

**Comment by rgstori** [comment]
> > > Please provide also the editable variant also of the file.
> > 
> > 
> > @tomkivlin do you happen to know where is the source pptx for this please?
> 
> In the /figures directory: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/kubernetes/figures/k8s-ref-arch-figures.pptx

@petorre would you mind updating the linked file as well please?

**Comment by petorre** [comment]
Now I updated .pptx and .png versions.

**Review by CsatariGergely — APPROVED** [review]

**Review by ulikleber — APPROVED** [review]

**Review by rgstori — APPROVED** [review]

**Comment by rgstori** [comment]
thanks! can't merge myself for some reason, will flag it's ready to @scottsteinbrueck

**Pull request merged**
