### PR TITLE
[RA-1 Ch02 ] Remove Compute intensive from req.

### PR DESCRIPTION
**Pull request by ASawwaf**
[RA-1 Ch02 ] Remove Compute intensive from req.

### CODE REVIEW

**Comment by pgoyal01** [comment]
@ASawwaf The "compute intensive" is commented out and is not visible in the document view. In RA-1 we have commented out "compute intensive" rather than delete. Is that not acceptable?

**Comment by ASawwaf** [comment]
@pgoyal01 as per @rabi-abdel he preferred to remove it totally 

@rabi-abdel please advice

**Comment by rabi-abdel** [comment]
> @pgoyal01 as per @rabi-abdel he preferred to remove it totally
> 
> @rabi-abdel please advice

@ASawwaf it has been removed by commenting it out (meaning it will not show in the rendered version of the documentation). Commenting it out is the approach we took (it will NOT be shown in the rendered version of the document).

**Comment by ASawwaf** [comment]
@rabi-abdel great I like it :)
thx

**Comment by rabiabdel** [comment]
based on discussion above, will close

**Pull request closed without merging**
