### PR TITLE
[RM Ch04] Remove PM taken by external instruments

### PR DESCRIPTION
**Pull request by xavier-grall**
Resolving #378 (including sections & tables renumbering)

### CODE REVIEW

**Comment by markshostak** [comment]
@xavier-grall Hi Xavier, Thank you for all of the effort you put in this commit, it is obvious you were doing a meticulous job. There is an issue, in that the plan for the PMs, as had been discussed in the last several RMCH-2/4/5 meetings, isn't reflected in the commit. Notably, we're not removing PMs altogether, we're only removing the _specific_ PMs that were relocated to RC/RMCH-8. I have an edit open and was thinking I'd just combine mine with yours, but after careful review, I'm afraid we need to revert. If you'd like to discuss/align, we can set up a time on Thr or Fri, just let me know. Thanks, -Mark

**Comment by xavier-grall** [comment]
@markshostak 
In my opinion, only PMs of section 4.1.3.1 and 4.1.5.1 have to move in chapter 8, since they are related to testing.
And PMs of section 4.1.3.4, which are rather related to monitoring capabilities, should stay in chapter 4.
Also, that section could be renamed "performance **monitoring** capabilities" or " **utilization monitoring** capabilities".

**Comment by markshostak** [comment]
@xavier-grall 
"only PMs of section 4.1.3.1 and 4.1.5.1 have to move in chapter 8" - Agreed, and those are the only tables that moved.
"section could be renamed "performance monitoring capabilities"" - Which section, specifically? The only section I see that qualifies, is Section 4.1.2.3 (using original section numbering).
Thx, -M

**Comment by xavier-grall** [comment]
@markshostak sorry it is 4.1.4.4 (but not 4.1.3.4) that could be renamed

**Comment by xavier-grall** [comment]
replaced by #520

**Pull request closed without merging**
