### PR TITLE
[RI1] update the index to include HDV contents

### PR DESCRIPTION
**Pull request by fuqiao123**
1. create a new chapter for hardware delivery verification(HDV)
2. update the progress of the chapter (please review to see if these progress are accurate)

### CODE REVIEW

**Comment by rabiabdel** [comment]
Hi @fuqiao123 this introduces new chapter which will impact the numbering in all other chapters: 
can you please include in this PR:
- the file for the new introduced chapter.
- the change needed to filenames for other chapters (since the naming will be shifted by one)
- the change in titles, headings, etc for all chapters impacted.

**Comment by lylavoie** [comment]
I think this will also have impact on the RC1 chapters too, since hardware verification was intended to be part of the reference certification as well.  Should we do those change as one pull request to keep things synced up.

**Comment by fuqiao123** [comment]
> Hi @fuqiao123 this introduces new chapter which will impact the numbering in all other chapters:
> can you please include in this PR:
> 
> * the file for the new introduced chapter.
> * the change needed to filenames for other chapters (since the naming will be shifted by one)
> * the change in titles, headings, etc for all chapters impacted.

OK. Will do that

**Comment by fuqiao123** [comment]
> I think this will also have impact on the RC1 chapters too, since hardware verification was intended to be part of the reference certification as well. Should we do those change as one pull request to keep things synced up.

Personally I am not familiar with the RC doc, so I don't know if there is a chapter in RC that should capture the verification of hardware.

**Comment by gkunz** [comment]
Hi, @fuqiao123, @lylavoie. Hardware validation can be included in chapter 3 of RC1, at least on a high level as it is mentioned there. Depending on the length and level of detail of this topic, it could later be moved to a separate chapter.

**Comment by mf4716** [comment]
Consider moving / adding HDV (& it's compliment, Manifest Validations) are part of an RI delivery, or Lab Ops.  These tools will provide additional verification / validation of target state lab delivery.  These strategies are mentioned in the RC-x validation materials.  

Here's a excerpt from CNTT RI 1 Labs material, which could be retrofitted to include HDV & Manifest Validations:

**Scope**
: Procure initial target lab
: Ensure all entry / exit criteria met --> **HDV and Manifest perform this verification**
: Assist with lab selection options (LAAS, Community, Self Service)
: Release Alignment 

Ch04: Lab Requirements
Ch06: Lab Operations --> **"add verification/validation tools"**

**Comment by fuqiao123** [comment]
According to our discussion on this week's RI/RC call, could reviewers please approve this PR merge?
@rabi-abdel @collivier @rrajesh70

**Pull request merged**
