### PR TITLE
Ch01 (1.5 Scope)

### PR DESCRIPTION
**Pull request by rabiabdel**
Place holder to clarify the relation between RM, RA, and RI. it is also to update the scope figure.

### CODE REVIEW

**Comment by BernardTsai-DT** [comment]
I still believe that the VIM is to be regarded part of the NFVI SW layer and therefore should be included into scope of the Reference Model. And when we will be talking about Reference Architectures I would imagine that the typical APIs e.g. OpenStack, OpenContrail, etc. would be the actual APIs which the NFVI would expose from a management perspective.

**Comment by rabiabdel** [comment]
> I still believe that the VIM is to be regarded part of the NFVI SW layer and therefore should be included into scope of the Reference Model. And when we will be talking about Reference Architectures I would imagine that the typical APIs e.g. OpenStack, OpenContrail, etc. would be the actual APIs which the NFVI would expose from a management perspective.

agreed, will reflect it in the text/diagrams

**Comment by rabiabdel** [comment]
@BernardTsai-DT Changes made to diagram as discussed!

**Comment by rabiabdel** [comment]
replace figure to say VIM and approved afterwords

**Pull request merged**
