### PR TITLE
[RM Ch08]: Replacing NFVI and instance type

### LINKED ISSUE #1168: [RM] generic requirements of CNF in RM3.3 and RM4.1
@tomkivlin we have some observation in RM stream . It looks the requirements are too much VNF focused and not scoped adequately for CNF .

E.g 4.1 Capabilities and Performance Measurements we can find VIM performance but not  K8S platform capabilities part 

3.3 NFVI Management Software is another example we expect something like container management as well 
Similarly for K8S at minimum performance requirements , CRD's and CRI-O etc should be included

I am sure it is included somewhere can you ignore my negligence if so and help us understand how you are tacking it .

### PR DESCRIPTION
**Pull request by EditKoselak**
Partially closes #1168 and #1209

### CODE REVIEW

**Comment by CsatariGergely** [comment]
We would need the source of the figures in Ch8. They are not in [CNTT_diagrams.pptx](https://github.com/cntt-n/CNTT/blob/master/artefacts/CNTT_diagrams.pptx). Any idea from whom could we get them? @rabi-abdel , @kedmison ?

**Comment by kedmison** [comment]
> We would need the source of the figures in Ch8. They are not in [CNTT_diagrams.pptx](https://github.com/cntt-n/CNTT/blob/master/artefacts/CNTT_diagrams.pptx). Any idea from whom could we get them? @rabi-abdel , @kedmison ?

Sorry, if they are not there then I do not know.  Can you look at who submitted image updates to see who might have created them in the first place?

**Comment by EditKoselak** [comment]
> > We would need the source of the figures in Ch8. They are not in [CNTT_diagrams.pptx](https://github.com/cntt-n/CNTT/blob/master/artefacts/CNTT_diagrams.pptx). Any idea from whom could we get them? @rabi-abdel , @kedmison ?
> 
> Sorry, if they are not there then I do not know. Can you look at who submitted image updates to see who might have created them in the first place?

It looks like the figures were committed by @mf4716. Michael, could you please send us the source files?:)

**Comment by kedmison** [comment]
@EditKoselak @CsatariGergely FYI: Chapter 8 is about to be substantially re-written, and potentially even the figures may be dropped. 
@markshostak what do you think about merging this change or dropping it given the upcoming Chapter 8 change?

**Comment by markshostak** [comment]
> 
> @markshostak what do you think about merging this change or dropping it given the upcoming Chapter 8 change?

I'd say merge it now, before we purge it, just to make like a little easier for the RC1 team and @collivier. I'll approve it, to try to speed it up.
-M

**Comment by markshostak** [comment]
P.S. Don't waste time on the figures at this point. We can pull the source file if we need it, but I don't see a need at this juncture. Thx, -M

**Comment by markshostak** [comment]
@kedmison Hi Kelvin, Can we merge this PR, so @collivier can rip RMCH8 out and close the other PR? Thanks, -Mark

**Comment by kedmison** [comment]
@markshostak should we just close this PR and rip chapter08 out, rather than the other way around?

**Comment by markshostak** [comment]
> 
> @markshostak should we just close this PR and rip chapter08 out, rather than the other way around?

The intent was that we'd merge these changes before the content was moved, but I think that ship has sailed, so yes, let's close it. Thx, -Mark

**Pull request closed without merging**
