### PR TITLE
[ra2 ch3] fix build errors

### PR DESCRIPTION
**Pull request by rgstori**
fixing build errors

./chapters/chapter03.rst:614: D000 Malformed table.
Multiple head/body row separators (table lines 3 and 8); only one allowed.

D002 Trailing whitespace

D000 Inline emphasis start-string without end-string.

D000 Inline interpreted text or phrase reference start-string without end-string

fix double colon in link:
`/home/opnfv/slave_root/workspace/cntt-tox-ra2/doc/ref_arch/kubernetes/chapters/chapter02.rst:447:undefined label: ref_model/chapters/chapter08:chapter 8 hybrid multi-cloud: data centre to edge
ERROR: InvocationError for command /home/opnfv/slave_root/workspace/cntt-tox-ra2/doc/ref_arch/kubernetes/.tox/docs/bin/sphinx-build -W -b html . build (exited with code 2)
`

### CODE REVIEW

**Comment by pgoyal01** [comment]
@rgstori I am approving but can you correct a typo on line 594 -- "Built in Kubernetes Network Functionality" to "Built-in Kubernetes Network Functionality"; add a hyphen between "Built" and "in". Thanks.

**Review by pgoyal01 — APPROVED** [review]

**Comment by rgstori** [comment]
> @rgstori I am approving but can you correct a typo on line 594 -- "Built in Kubernetes Network Functionality" to "Built-in Kubernetes Network Functionality"; add a hyphen between "Built" and "in". Thanks.

sure, thanks for catching that.
am fixing all the build errors in this PR so will adjust the title in a minute

**Comment by rgstori** [comment]
@collivier the links to RM are throwing an error, I'm not sure if this is the right way to use :ref: directives, does it look ok to you?
build 1361 throws:
`/home/opnfv/slave_root/workspace/cntt-tox-ra2/doc/ref_arch/kubernetes/chapters/chapter02.rst:447:undefined label: ref_model/chapters/chapter08:chapter 8 hybrid multi-cloud
ERROR: InvocationError for command /home/opnfv/slave_root/workspace/cntt-tox-ra2/doc/ref_arch/kubernetes/.tox/docs/bin/sphinx-build -W -b html . build (exited with code 2)
`

in the rst file I have: 

>The Reference Model :ref:\`ref_model/chapters/chapter08:chapter 8 Hybrid Multi-Cloud\`

**Comment by pgoyal01** [comment]
@rgstori The format for the reference needs to be
         :doc:`ref_model/chapters/chapter08:Hybrid Multi-Cloud Architecture`

**Review by collivier — APPROVED** [review]

**Pull request merged**
