### PR TITLE
[CNTT TSC] Clarifying Scope for WS

### PR DESCRIPTION
**Pull request by rabi-abdel**
- most importantly RI and RC.

### CODE REVIEW

**Comment by rabi-abdel** [comment]
Note: There is no content change, simply adding scope section to chapter 1 and some restructuring to RC WS to make it less confusing (without removing or adding content).

**Comment by rabi-abdel** [comment]
@mf4716 are you happy with the new modified structure? if so, please approve. this is very minor update.

**Comment by rabiabdel** [comment]
passed the cooling off period, no further input received.

**Comment by collivier** [comment]
There are lots of content removed which I hope it's a human mistake (see 8.2, 9.2, 9.3, etc.)
I ask for a quick revert of this disruptibe change.

**Pull request merged**
