### PR TITLE
[RC1] Fill all gaps already tracked as issues in CNTT

### PR DESCRIPTION
**Pull request by collivier**
Port VTP test cases to Xtesting [1] is key because the TC doesn't conform
to the principles and requirements defined.

https://github.com/cntt-n/CNTT/issues/917

Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>

### CODE REVIEW

**Comment by collivier** [comment]
@rabiabdel @rabi-abdel hoping it will be merged as it's the current gap analysis as highlighted in CNTT bug tracker. Let's see if new CNTT developers will take the actions. Nothing has been treated for this cycle out the first ones for Functest (not listed here as done)

**Comment by rabiabdel** [comment]
@mf4716 @phrobb @karinesevilla can we get another approval for this to be merged?

**Comment by collivier** [comment]
This issues explained a little bit more. I can add 1 or 2 sentences if I'm still on time.

The gap here is mostly about testing and by the existing OPNFV test frameworks which doesn't support yet the current model. Then we can't smoothly leverage on the current testcase which could hel RC (disk benchmarking, HA, etc.)

VTP (Chapter 5) does support the CI model via small adaptations. We souldn't force one CI for NFVI and one CI for VNF testing

**Comment by rabi-abdel** [comment]
> This issues explained a little bit more. I can add 1 or 2 sentences if I'm still on time.
> 
> The gap here is mostly about testing and by the existing OPNFV test frameworks which doesn't support yet the current model. Then we can't smoothly leverage on the current testcase which could hel RC (disk benchmarking, HA, etc.)
> 
> VTP (Chapter 5) does support the CI model via small adaptations. We souldn't force one CI for NFVI and one CI for VNF testing

@collivier yes please, go ahead. I will merge later tonight. you might still have 1-2 hours.

**Comment by collivier** [comment]
@rabi-abdel @rabiabdel @mf4716 It should avoid confusion. I would detail the JIRA issues if needed.

**Pull request merged**
