### PR TITLE
Update Chapter 03.md

### PR DESCRIPTION
**Pull request by pgoyal01**
Added preliminary content -- still WIP

### CODE REVIEW

**Comment by pgoyal01** [comment]
@walterkozlowski Agree about Ceilometer and Prometheus -- would like us to decide on a direction; in Paris Ceilometer was presented as part of the Reference Architecture.

**Comment by pgoyal01** [comment]
Should we specify a base Host OS or Kernel base version?

**Comment by ASawwaf** [comment]
> @walterkozlowski Agree about Ceilometer and Prometheus -- would like us to decide on a direction; in Paris Ceilometer was presented as part of the Reference Architecture.

my recommendation to go with Prometheus ( or similar approaches Sensu , Collectd , telegraf )  as in real deployment ceilometer cannot scale at all

**Comment by ASawwaf** [comment]
> Should we specify a base Host OS or Kernel base version?

i dont think so

**Comment by rabi-abdel** [comment]
@pgoyal01 great work. the one thing I would say this requires a lot of stripping down as the content shown here is more component level than High Level. The focus of this chapter needs to be on the interfaces northbound (towards VNFs) and VIM. high level Networking Fabric.

**Comment by rabi-abdel** [comment]
@pgoyal01 please update prior meeting to only include outline proposal.

**Comment by rabi-abdel** [comment]
DEFERED

**Pull request closed without merging**
