### PR TITLE
Chapter 3 Cleanup PR

### PR DESCRIPTION
**Pull request by markshostak**
This PR will capture commits related to the Chap 3 cleanup.

### CODE REVIEW

**Comment by mtoy54** [comment]
Please add the following to Section 3.2.

[section3.2.docx](https://github.com/cntt-n/CNTT/files/3375509/section3.2.docx)


 
![im

**Comment by mtoy54** [comment]
Please include the following additional text.
[section3.2-second-comment.docx](https://github.com/cntt-n/CNTT/files/3375649/section3.2-second-comment.docx)

**Comment by mtoy54** [comment]
I just realized my previous contribution was not included.  Without incorporating my previous contribution for section 3.2,  it would be difficult to tie my two comments that I just posted.  Here, I am attaching my earlier contribution so that we can discuss all at the same time.
[CNTT_Ref_Model_MVP_v0.11_clean-sections 3.1-3.2-3.5-updates-mtoy.docx](https://github.com/cntt-n/CNTT/files/3375657/CNTT_Ref_Model_MVP_v0.11_clean-sections.3.1-3.2-3.5-updates-mtoy.docx)

**Comment by pgoyal01** [comment]
Mehmet,
Can we add these to Chapter 7: APIs restricting only to NFVI; interfaces to the VNF layer would be out-of-scope.

**Comment by markshostak** [comment]
> I just realized my previous contribution was not included. Without incorporating my previous contribution for section 3.2, it would be difficult to tie my two comments that I just posted. Here, I am attaching my earlier contribution so that we can discuss all at the same time. [CNTT_Ref_Model_MVP_v0.11_clean-sections 3.1-3.2-3.5-updates-mtoy.docx]

Mehmet, This PR is focused on cleanup. Please create a new PR to add your material, but given the scope I think we should add it after Paris. It's a lot to integrate in the few remaining days when we're focused on cleanup. Thanks, -Mark

**Comment by mtoy54** [comment]
Pankaj,
I think so.
After discussions, if we need to move it around we can.
Thanks!
Mehmet

**Comment by rabiabdel** [comment]
HI @markshostak what is the next step for this Pull Request?

**Comment by pgoyal01** [comment]
Rabi,

Some of us (Bernard, Herbert, Karine, Walter and me) had met and decided on the content of the model (Bernard's section). I had entered the changes. Mehmet has suggested some adds. We should discuss his suggestions tomorrow (Friday July 12). I had suggested to Mehmet that since his adds are related to APIs that it likely belongs under Chapter 7 except for the Interfaces for the VNF layer.

**Comment by rabiabdel** [comment]
> I had entered the changes

@pgoyal01 where have you entered the changes?

if you entered them in your own branch, you need to create a pull request from them. check the slides i shared earlier of how to do that.

Yours,
Rabi

**Comment by rabiabdel** [comment]
will merge after the meeting by resolving conflicts

**Pull request merged**
