### PR TITLE
Chapter 01 (Terminology + Principles) 

### PR DESCRIPTION
**Pull request by pgoyal01**
Added the Terminology and principles that were agreed on Monday June 24, 2019.

### CODE REVIEW

**Comment by rabiabdel** [comment]
Hi @pgoyal01, thanks for submitting this. 

few comments:

- I was  it expecting changes to principles, can we make this focused on terminology only? 
- my expectation was that this will provide definition to the terminologies we defined last Friday. I see many many new terminologies such as vApp which is very VMware specefic.
This Pull Request replaces the entire terminology section with a new one instead of clarifying the definition of those terminologies already exist there as was expected. 
Can we do this in few phases:
1- clean up what we have in there by filling up the missing definition with what was discussed last Monday.
2- if new terminology is needed, a new pull request to be added for them.

**Comment by rabiabdel** [comment]
Thanks @pgoyal01

**Comment by pgoyal01** [comment]
Rabi,
As you know when we met on Monday June 24th and Tuesday June 25th, the participants agreed to the terminology and principles. 

I decided to do a mass change since nearly every existing term was affected in some way or shape.
vApp is now defined in the referenced ETSI 1.4.1 (2018-10) document.

I can make the changes in multiple phases but it would be easier if the totality of changes could be agreed upon as there were.

Thanks
Pankaj

**Comment by rabiabdel** [comment]
OK thanks. Enjoy your weekend.

**Comment by rabiabdel** [comment]
Hi @pgoyal01 : 

we have been differentiating the term profile form configuration. 
Therefore, can you please :

**_Replace_** 

**NFVI Software Profile/Flavour**: defines the compute, memory, and storage capacity of a virtual compute resource. Note: used to define the configuration/capacity limit of a virtualised container.
**NFVI Hardware Profile**: defines the configuration of compute, storage and networking of a hardware server.

**_with:_**

**NFVI Software Profile**: This defines the behaviour, capabilities and metrics provided by an NFVI Software Layer. 
**NFVI SW Configuration**: is a set of settings (Key:Value) that are applied to NFVI SW layers to behalf as their corresponding NFVI SW Profile. 
**NFVI Hardware Profile**: This defines the behaviour, capabilities and metrics provided by an NFVI Hardware Layer. 
**NFVI HW configurations**: is a set of settings (Key:Value) that are applied to NFVI HW layers to behalf as their corresponding NFVI HW Profile.

Thank you

**Comment by pgoyal01** [comment]
Rabi,

These changes will force a major rewrite of multiple chapters. Do you have examples of how the behavior and capabilities will be specified for NFVi Software and NFVi Hardware profiles?

Best regards,
Pankaj
--------
pg683k@att.com | w  720.475.4530  |  m 720.327.0104

**Comment by rabiabdel** [comment]
Hi @pgoyal01 : Pretty much the concept of profile in the document has been used to present capabilities and behaviors. Pretty much all tables in Chapter 3 has been written with this in mind. 

Hope this makes sense.

**Comment by hdamker** [comment]
Three small comments:

- VNF and Virtual Network Functions (VNF) are duplicates
- Compute Nodes are only physical servers, the term is not used for virtual servers
- There is no such term like "NFVi Orchestrator" in ETSI NFV 003 v.1.4.1 ... only NFVO (which i consider out of scope here)

**Comment by hdamker** [comment]
> Hi @pgoyal01 : The concept of profile in the document has been used to present capabilities and behaviors so far. I feel, it is otherwise, that we will have to re-write pretty much the whole document. All capabilities and metrics tables in Chapter 3 has been written with this in mind.
> 

First I thought I have understood the "profiles" in the paper, but as someone who not followed all the discussions I'm similar confused then Pankaj:

Beside "NFVI Software Profile" and "NFVI Hardware Profile" there is actual a third "profile" term later in chapter 2 and chapter 4: the "infrastructure profile" (as in "infrastructure profile catalog"). Actual these profile is a "virtual infrastructure resource profile" or "virtual infrastructure resource flavor".

Can we make this more explicit in the document. "Infrastructure profile" could easily be confused with NFVI profile (= NFVI Software + NFVI Hardware profile). 

See also my comment https://github.com/cntt-n/CNTT/pull/16#discussion_r299231637

**Comment by mtoy54** [comment]
Please see PNF and Workload definitions below.

[PNF-workload-definitions.docx](https://github.com/cntt-n/CNTT/files/3348055/PNF-workload-definitions.docx)

**Comment by markshostak** [comment]
Per PG, update to be completed by next Monday.
PG to update terms in chapter 1
PG to provide reference for vApp

**Comment by rabiabdel** [comment]
Too many comments and edits suggestions. I tried to consolidate them by creating a new pull request addressing all comments: https://github.com/cntt-n/CNTT/pull/41

**Comment by rabiabdel** [comment]
Hi @pgoyal01 I have added few diagrams to explain the terminology used. Please have a look and let me know. The definitions used in the new one are  exactly the same one used in here. The only difference is the order and adding the diagrams. Also I incorporated Karine suggestions. Let me know if you are OK with it.

**Comment by rabiabdel** [comment]
Hi @pgoyal01 if you are OK with the terminology consolidation Pull Request, can you remove the terminology changes from here and keep this Pull Request for the Principles Changes you are proposing so we can approve this Pull request  tomorrow?

**Comment by rabiabdel** [comment]
Closed, need to re-create a new pull request against the latest master

**Pull request closed without merging**
