### PR TITLE
[RM Ch08]: Removing incorrect definitions

### LINKED ISSUE #429: [RM Ch8]: Definitions of attributes are not correct
Definitions of i.nfvi.mon.cap.005 and 006 are not correct, and in case of i.nfvi.mon.cap.002 I do not see how „QoS enablement” is connected to „Virtual compute resource CPU usage” monitoring.

### PR DESCRIPTION
**Pull request by CsatariGergely**
The definitions of i.nfvi.mon.cap.005 and 006 were incorrect.

For some reason the same attributes are listed in both Chapter 4
and Chapter. At the moment I've fixed this in both places, but it
would be better if we would remove the attributes from one of the
chapters.

Fixes #429

### CODE REVIEW

**Comment by rabi-abdel** [comment]
@CsatariGergely would you mind please resolving the conflict above? it seems the fork (or branch) you use for this PR is out of date!

**Comment by CsatariGergely** [comment]
> 
> 
> @CsatariGergely would you mind please resolving the conflict above? it seems the fork (or branch) you use for this PR is out of date! in fact, RM Ch08 proposed changes, can you please make those changes directly into #579 (submit a commit into that PR). this way it will be easier to resolve. and keep this PR for Ch04 only. hope this is OK.

Done

**Comment by rabi-abdel** [comment]
> > @CsatariGergely would you mind please resolving the conflict above? it seems the fork (or branch) you use for this PR is out of date! in fact, RM Ch08 proposed changes, can you please make those changes directly into #579 (submit a commit into that PR). this way it will be easier to resolve. and keep this PR for Ch04 only. hope this is OK.
> 
> Done

mmm not sure what you have done here :) my thinking was is to keep this PR for Chapter 4 and any change needed for Chapter 8 to be made directly in #579

**Comment by rabi-abdel** [comment]
@CsatariGergely if the modification you propose here can be reflected in #579 PR, we can close this one?

**Comment by CsatariGergely** [comment]
> 
> 
> @CsatariGergely if the modification you propose here can be reflected in #579 PR, we can close this one?

Humm, I think yes we can close this. If I understand this correctly #579 moved these to RC (what is by the way still called certification) and deleted them.

**Comment by rabi-abdel** [comment]
> > @CsatariGergely if the modification you propose here can be reflected in #579 PR, we can close this one?
> 
> Humm, I think yes we can close this. If I understand this correctly #579 moved these to RC (what is by the way still called certification) and deleted them.

feel free @CsatariGergely to update #579 by pushing commits in there. it is requiring your approval atm anyway.

**Pull request closed without merging**
