### PR TITLE
RA2 Ch2 - remove LCM requirements

### LINKED ISSUE #616: [RA2 Core] Requirements: The Architecture **must** support hitless upgrades of software provided by the cloud provider so that the availability of running workloads is not impacted
This is a highly problematic requirement. A cloud-native best practice is that the cluster admin (or any automation built on top) would "kubectl drain" pods from a node, which signals pods to drain their sessions and state and terminate within the grace period or be force-terminated. Following maintenance (upgrades, rollback, whatever) the node would be uncordoned.

*Moving the responsibility for availability from the workloads back to the platform and asking for "hitless upgrades" of the platform (which would include firmware, kernel, etc.) is an absolute cloud anti-pattern.*

_Originally posted by @fzdarsky in https://github.com/cntt-n/CNTT/pull/452/files_

### LINKED ISSUE #1207: [RA-2 CH01] LCM is out of scope -- but required
Chapter 1 says that 'For the avoidance of doubt, the following is considered to be out of scope:  Kubernetes cluster lifecycle management: reason being, it is not considered to be "visible" to a CNF and so should not be included.'

However, multiple locations say things like "req.inf.ntw.09 | Network | The Architecture must support API driven life-cycle management (LCM) of the infrastructure that allows repeatable, scalable and standardised handling of K8s clusters. LCM use cases to cover are: instantiation, termination, upgrade, scaling, and healing."

So is it in scope or not?

### PR DESCRIPTION
**Pull request by tomkivlin**
Fixes #616
Fixes #1207

### CODE REVIEW

**Comment by tomkivlin** [comment]
An alternative could be to uncomment and reword to something like:
```
req.lcm.mnt.01 | Node Maintenance | The Architecture *must** support the ability for nodes to be drained of all running workloads to allow for ongoing maintenance processes.
```

**Comment by tomkivlin** [comment]
> Much better statement

Just want to check - what are you approving?  The removal of the requirement altogether (as per current commits) or replacing the requirement with the wording as my comment above?

**Comment by walterkozlowski** [comment]
@tomkivlin, I approved replacement with your wording. Apologies for confusion.

**Comment by hdamker** [comment]
@tomkivlin I can speak only for myself: I approved the actual committed change (removal). I would be fine with the proposed alternative formulation as well (but you argued in https://github.com/cntt-n/CNTT/issues/616#issuecomment-594500620 rightfully that this is a given, standard feature of K8S anyway).

To be able to approve the alternative text it would need to be in the PR.

**Comment by tomkivlin** [comment]
> @tomkivlin, I approved replacement with your wording. Apologies for confusion.

No problem.  I'll remove your approval for now otherwise it'll get merged. Also, TSM meeting today hoping to discuss whether LCM is in-scope or not.

**Comment by tomkivlin** [comment]
@hdamker I've marked the PR as on-hold for now whilst we debate LCM inclusion in scope or not.

**Comment by CsatariGergely** [comment]
- LCM is not in the scope, so the requirement can be removed
- `req.lcm.adp.03` should be also removed (with the whole comment block)
- merge is needed

**Comment by tomkivlin** [comment]
I have taken the opportunity to remove all requirements relating to LCM of Kubernetes / CaaS Clusters.

**Comment by tomkivlin** [comment]
> @tomkivlin, I approved replacement with your wording. Apologies for confusion.

Hi Walter - as the agreement is to remove LCM requirements, could you review again please?

**Pull request merged**
