### PR TITLE
[Reference Architecture] Ch 03 + Ch 04 outlines

### PR DESCRIPTION
**Pull request by iangardner22**
This PR will contain outline proposal for Chapter 4 (Level 3 artefacts). The content of Chapter 4 will go down to component level.

### CODE REVIEW

**Comment by rabi-abdel** [comment]
since we discussed this in length during the meeting, I will keep it open for 24 hours to receive further feedback before approving and merging it.

**Comment by pgoyal01** [comment]
@iangardner22 Some observations:

3.5 Workload Services: (i) should this also list Virtualisation Services; (ii) does Tenant Separation belong in this sub-section?

4.4.  Logging / Monitoring / Alerting (should this be a separate section on its own? 
              IMHO, yes as these also apply to Workload Services and the Infrastructure

4.5 Contrail
            Would this be Open Contrail (in line with requirements) or the Proprietary version?

In addition to addressing the Profiles in 4.5 and their software and Hardware components, should we also address the movement to "Any workload, any host" for resource utilization (no partitioning of the hosts by multiple profiles) and operational efficiencies?

**Comment by rabiabdel** [comment]
> @iangardner22 @rabi-abdel
> RA Chapter 03: 3.7 Interfaces & APIs can be deleted is a duplicate of 3.6
> 
> RA Chapter 04: should "4.2.1 Enabler Services" be part of "4.6 Integration/Interfaces"? If yes maybe we can get rid of the sub-section 4..2.2.

All incorporated.

**Comment by rabiabdel** [comment]
> should this also list Virtualisation Services

All incorporated

**Pull request merged**
