### PR TITLE
[ra2] fix ra2 date in readme

### PR DESCRIPTION
**Pull request by rgstori**

### CODE REVIEW

**Review by pgoyal01 — APPROVED** [review]

**Review by karinesevilla — APPROVED** [review]

**Review by collivier — CHANGES_REQUESTED** [review]
I would prefer us to remove this data which are not part of GSMA.
We should rather tag git repository with ra2 version if needed.

**Comment by collivier** [comment]
@rgstori @pgoyal01 another solution could be to leverage the only directive
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html

.. only:: html

**Comment by CsatariGergely** [comment]
> @rgstori @pgoyal01 another solution could be to leverage the only directive
> https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html
> 
> .. only:: html

I would prefer this option.

**Comment by rgstori** [comment]
would removing it work? as in #3071

**Comment by CsatariGergely** [comment]
I did remove the version information and moved it to a central place in #3077

**Pull request closed without merging**
