### PR TITLE
[CSO Ch02 - Gov] Initialized chapter name

### PR DESCRIPTION
**Pull request by jbeltranatl**
Rabi - my first pull requests! Yay! Now tell me what I did wrong if anything.

### CODE REVIEW

**Comment by rabiabdel** [comment]
Nothing wrong, it looks good. Not sure though why it is asking for my approval. I configured it to ask for yours. I will try to fix.

**Comment by rabi-abdel** [comment]
looks ok @jbeltranatl. the process is getting 3 approvals then you can merge it yourself as code owner.

**Comment by jbeltranatl** [comment]
Ok. What do I do know? :-)

**Comment by rabi-abdel** [comment]
you need to ask 3 reviewers to review it, but since this is an initial content, I recommend you ask any three to approve it and just to get it merged.

**Comment by rabi-abdel** [comment]
I did approve it. (you can't approve it yourself, since you are the one who created it)

**Comment by rabi-abdel** [comment]
in the top right hand side where reviewers are shown, if you click on the gear symbol, you can add reviewers to the Pull Request

**Comment by pgoyal01** [comment]
@jbeltranatl To be consistent and also for ease of understanding, the title of the Issue/PR should include [WS - Chapter #], for example, "[Gov - CSO Ch2] Initialised Chapter Name." Thanks

**Comment by jbeltranatl** [comment]
@rabi-abdel THANKS almost there. Can you add RT_ATT as user?

**Comment by rabiabdel** [comment]
> @rabi-abdel THANKS almost there. Can you add RT_ATT as user?

Done

**Comment by jbeltranatl** [comment]
@rabi-abdel weird. RT_ATT isn't pulling up as user. I'll give it some time.

**Comment by rabiabdel** [comment]
> @rabi-abdel weird. RT_ATT isn't pulling up as user. I'll give it some time.

They have to accept the invitation first

**Comment by rabiabdel** [comment]
You need one more approval b4 you can merge this

**Pull request merged**
