### PR TITLE
[RM Ch09] Update chapter09.md

### LINKED ISSUE #663: [RM Ch 9] OM&A requirements
@kedmison @trevgc , Gents as per our RM call, we need your support to define the requirements of 
OAM , Assurnace part of NFVi in terms of FM , Logging , Config mgt

### PR DESCRIPTION
**Pull request by ASawwaf**
Gents as per our RM call, we need your support to define the requirements of
OAM , Assurnace part of NFVi in terms of FM , Logging , Config mgt

Fixes #663

### CODE REVIEW

**Comment by rabiabdel** [comment]
@ASawwaf can you start the initial content to review?

**Comment by rabi-abdel** [comment]
any volunteers for more content or shall we approve the text here as is?

**Comment by markshostak** [comment]
@rabi-abdel I don't see any text here to approve. It looks like a place holder. Thx, -M

**Comment by rabiabdel** [comment]
> @rabi-abdel I don't see any text here to approve. It looks like a place holder. Thx, -M

@markshostak you are right. 

@ASawwaf will it be possible to provide the initial content for approval/discussion?

**Pull request closed without merging**
