### PR TITLE
[TSC]: Adding Walter as a generic code owner

### PR DESCRIPTION
**Pull request by CsatariGergely**

### CODE REVIEW

**Comment by gkunz** [comment]
Thank you, @CsatariGergely for creating this PR. I believe there is a misunderstanding, though. My question on today's TSC call was rather if we should replace @scottsteinbrueck with new code owners. Scott hasn't been active for a while and Walter seems to have to approve most of the PRs as code owner these days.

**Review by gkunz — CHANGES_REQUESTED** [review]
See my comment: My intention was rather to remove Scott and ideally replace him with new code owners.

**Comment by pgoyal01** [comment]
@gkunz Since WSLs are authorized to approve PRs in their WSs except those that they author, we have always had only one  main codeowner -- Rabi, Scott and now Walter.

**Comment by gkunz** [comment]
Hi @pgoyal01, you are right about that. However, then I am still in favor of cleaning up the code owners and removing Scott since his name gets automatically added to all PRs and I have seen people referring to him in comments asking for approval. I believe, this is also @walterkozlowski's opinion if I understood him correctly on the call.

There is also more room for cleanup, e.g., Fu Qiao (RC1) and Bill Mulligan (RC2).

**Comment by CsatariGergely** [comment]
I've removed Scott with 62d287d. I agree with @gkunz to clear RC1 and RC2 also. Can you remind me who should I add instead of Fu Qiao and Bill?

**Comment by pgoyal01** [comment]
@CsatariGergely RC1 and RC2 are both currently being run by @collivier

**Comment by gkunz** [comment]
Thanks for the update.

**Review by gkunz — APPROVED** [review]

**Comment by CsatariGergely** [comment]
> 
> 
> @CsatariGergely RC1 and RC2 are both currently being run by @collivier

It seems [not anymore](https://lists.anuket.io/g/anuket-tsc/topic/both_cntt_rc1_and_rc2_leads/85308120?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,85308120). 

I will leave only Walter there, then.

**Review by gkunz — APPROVED** [review]

**Review by walterkozlowski — APPROVED** [review]

**Pull request merged**
