### PR TITLE
[RA2 Ch2] Adding a new networking requirement to address scale

### PR DESCRIPTION
**Pull request by sukhdevkapur**
This addresses issue #1876

### CODE REVIEW

**Comment by tomkivlin** [comment]
@sukhdevkapur I fully support the intent of this PR.  Couple of comments:
1. Should this be at RM level (i.e. could it apply to all RAs)?
1. I think we need to be a bit more specific though, perhaps with multiple requirements.  For example, in the original issue you already have two (_Networking should scale across multiple clouds. There should be an ability to federate networks spanning across multiple deployments._) but more importantly what do we want to be able to scale?  Would a networking solution that has a single "visibility" plane but multiple disconnected control and data planes for each cloud count?  Or are we talking about being able to logically connect and control the networks from multiple clouds at e.g. IP layer from a single place?  Or something else?

I don't think we need loads more, but just a couple/few to explain what we want from multi-cloud networking would help determine the solutions.

**Comment by pgoyal01** [comment]
@sukhdevkapur @tomkivlin asked a couple of questions that remain un-addressed. My vote would be to add these requirements to the RM chapter and then they can be incorporated in the RAs.

If you do not want to add in RM then the requirement should be added in [Section 2.3](https://github.com/cntt-n/CNTT/blob/sukhdevkapur-patch-5/doc/ref_arch/kubernetes/chapters/chapter02.md#2.3) as Section 2.2 is titled [Reference Model Requirements](https://github.com/cntt-n/CNTT/blob/sukhdevkapur-patch-5/doc/ref_arch/kubernetes/chapters/chapter02.md#2.2)

**Comment by walterkozlowski** [comment]
@sukhdevkapur @tomkivlin @pgoyal01: I think that these are good candidates to be added to RM actaually

**Comment by tomkivlin** [comment]
OK thanks.  I have renamed the issue (#1876) and moved to RM project.  Closing this PR.

**Pull request closed without merging**
