### PR TITLE
[RM Ch3] Figure 3-9

### PR DESCRIPTION
**Pull request by petorre**
Figure from @TFredberg .
Figure 3-7 "Example SmartNIC Deployment Model That Accelerates Two Workloads and Has OOB Management"
Towards fixing #2051 .

### CODE REVIEW

**Review by CsatariGergely — CHANGES_REQUESTED** [review]
Please provide also an editable version of the file.

**Comment by petorre** [comment]
> 
> 
> Please provide also an editable version of the file.

Asked @TFredberg to provide, will add then.

**Comment by petorre** [comment]
> > Please provide also an editable version of the file.
> 
> Asked @TFredberg to provide, will add then.

@CsatariGergely : Done.

**Comment by walterkozlowski** [comment]
@petorre, I am approving hoping that the editable version is also provided

**Review by walterkozlowski — APPROVED** [review]

**Comment by petorre** [comment]
> @petorre, I am approving hoping that the editable version is also provided

@walterkozlowski : Yes, it is already added.

**Review by pgoyal01 — APPROVED** [review]

**Pull request merged**
