### PR TITLE
Edge use cases to be moved to RM_CH02

### LINKED ISSUE #1751: [RM Ch02.] Add use cases to sec 2.2

### PR DESCRIPTION
**Pull request by ASawwaf**
closes #1751

### CODE REVIEW

**Comment by pgoyal01** [comment]
@ASawwaf This PR states "Edge use cases to be moved to RM_Ch02. While the usecases have been deleted from doc/common/usecases.md but (i) they have not been moved to an RM chapter, and (ii) the file  doc/common/usecases.md has not been deleted.

**Comment by rabi-abdel** [comment]
The second half of this PR is in here: https://github.com/cntt-n/CNTT/pull/1810

**Comment by walterkozlowski** [comment]
@rabiabdel. @TFredberg, @karinesevilla - this sis done, please approve so I can close.

**Comment by pgoyal01** [comment]
Why is @walterkozlowski not showing up as code owner? It is waiting for @scottsteinbrueck to approve as code owner.

**Pull request merged**
