### PR TITLE
[RC Ch06] Update chapter06.md

### PR DESCRIPTION
**Pull request by yangyanyj**
Update chapter06, add the test case list and update some other content, please help review

### CODE REVIEW

**Comment by yangyanyj** [comment]
@mf4716  , in ch06, you drafted the intitial content framework, about the following 

6.5 Interaction Type
6.6 Performance Profiles

About these two items,what information do we need to provide? could you share you thoughts? Thanks

**Comment by mf4716** [comment]
@yangyanyj ,

Please do confirm with @mkr1481 (Kanag) and @sparayil (Shiby), but here are my thoughts with regards to framework for sections 6.5 and 6.6:

6.5 Interaction Type - these are the types, or list of potential interactions we have to write test case requirements for to support the certification frameworks.  For example, we may put a list together like this:
- vnf-req.[type].001 - to denote a functional requirements of type interopable, and being #1 in the sequence, followed by some descriptor like, "vnf-req.interoperable.001 - the infrastructure will support the ability to instantiate, communicate (ping, health-check, etc), and remove (tear down) a VNF", or "vnf-req.ha.001 - the infrastructure will support high availability, and sent requests to alternate VMs/VNFs when communication to a targeted VNF exceeds defined time-to-live policies".  The same would be repeated for any type of Edge (Complex), Functional, Fault, etc type requirements.

6.6 Performance Profiles - these are the stated infrastructure requirements for the various families of VNFs.  Families are roughly, "Basic, Network, Compute" intensive, and have infrastructure requirements as defined in RM and RA requirements.  See the following URLs for supporting information about requirements, which then help define the test requirements for performance.  We also need to make a statement that performance "KPIs - Key Performance Indicators" will be satisfied by the infrastructure for the B/N/C type VNF families.  Then, we need to define the ranges and targets for the KPIs, including any acceptable deviation.  Here are the requirements URls I mentioned:
o	RM 5: https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/chapters/chapter05.md --> model requirements
o	RA 2: https://github.com/cntt --> NFVI infra requirementsn/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter02.md
o	RA 5: https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/chapters/chapter05.md --> Compliance APIs

**Comment by yangyanyj** [comment]
Could you help review and merge this, I will move forward to add some other sections. Thanks

**Comment by mf4716** [comment]
> Could you help review and merge this, I will move forward to add some other sections. Thanks

@yangyanyj , I would recommend continue to edit the draft, and add your commits, along with other authors.  Once we're satisfied with content, say Tues this week, we can then ask for approvals and request merge from @rabi-abdel .  This will be faster than small edits, with merges each time.

**Comment by yangyanyj** [comment]
@mf4716 , sure, that's ok,  I will add other section base on this branch

**Comment by mf4716** [comment]
> @mf4716 , sure, that's ok, I will add other section base on this branch

Thanks!

**Comment by yangyanyj** [comment]
@sparayil , could you help review and give some comment about the sections 6.5 and 6.6,  could you share you thoughts?

**Pull request merged**
