### PR TITLE
[Technical Steering] Create label.yml

### LINKED ISSUE #623: [Technical Steering] Implement Auto-Labler
To minimise the number of clicks a contributor has to do, GitHuib has a mechansim to apply labels to PRs automatically based on what files they are changing.

### PR DESCRIPTION
**Pull request by rabiabdel**
Fixes #623

### CODE REVIEW

**Comment by CsatariGergely** [comment]
It would be nice to get this working. I've made an attempt, but it was not succesfull. 
You need to add a .github/labeler.yaml file where you match the labels to the path-s, like this: https://github.com/CsatariGergely/CNTT/blob/master/.github/labeler.yml

**Comment by rabiabdel** [comment]
> It would be nice to get this working. I've made an attempt, but it was not succesfull.
> You need to add a .github/labeler.yaml file where you match the labels to the path-s, like this: https://github.com/CsatariGergely/CNTT/blob/master/.github/labeler.yml

indeed! i am going through the documentation and hopefully it will work. finger xossed :)

**Comment by rabi-abdel** [comment]
I an not sure if this is going to work, but worth the try

**Comment by rabi-abdel** [comment]
can we get two to approve this we can test it as per meeting today?

**Comment by walterkozlowski** [comment]
Great if this works automatically and if we have an appropriate selection of labels

**Pull request merged**
