### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by rihabbanday**
Adding Dan Xu as RI2 PTL

### CODE REVIEW

**Comment by collivier** [comment]
Github highlights a possible issue with this account? Is it the right github one?

**Comment by rihabbanday** [comment]
@xudan16 could you please check if you have write access to this repository?

**Comment by gkunz** [comment]
@CsatariGergely can you add @xudan16 to the CNTT org?

**Comment by xudan16** [comment]
@rihabbanday @collivier @gkunz Done. I have write access now.

**Review by xudan16 — APPROVED** [review]

**Review by gkunz — APPROVED** [review]
LGTM

**Review by collivier — APPROVED** [review]

**Pull request merged**
