### PR TITLE
[RM Ch08] Purge Content Moved to RC

### PR DESCRIPTION
**Pull request by markshostak**
Cleaning out chapter 8 so people don't waste time "fixing" it, before we've started the new content.

### CODE REVIEW

**Comment by ASawwaf** [comment]
@markshostak @kedmison , shall we close this and WIP to move CH8

**Comment by markshostak** [comment]
> 
> @markshostak @kedmison , shall we close this and WIP to move CH8

@ASawwaf Hi Ahmed, 1366 is already merged, so the WIP is done. This was intended to save people from wasting their time, as several people seem to have been fixing content we're going to delete. Do you have any concerns w/ approving the PR at this time?

Hi, @collivier @CsatariGergely @petorre Same question, are there any concerns or can we approve this PR at this time?
Thanks,
-Mark

**Comment by ASawwaf** [comment]
@markshostak  , No at all :)  , I will approve it, we need to merge it

**Comment by rabi-abdel** [comment]
@fuqiao123 can you please review/approve?

**Pull request merged**
