### PR TITLE
[RA2 Ch04] Added statement to not restrict container base OS

### PR DESCRIPTION
**Pull request by peterwoerndle**
This addresses the OS modularity requirement discussed in Prague and in #950 .

### CODE REVIEW

**Comment by fkautz** [comment]
We should add that a version of a Linux kernel capable of running modern Linux containers at the very least.

Vendors may also have their own requirements. E.g. a vendor utilizing kernel based wireguard will need a much more modern kernel.

**Comment by YuPengZTE** [comment]
@peterwoerndle, could you add some examples for easy understanding?

**Comment by peterwoerndle** [comment]
@fkautz We do have a requirement on the HostOS kernel version to be 3.10+ in table 4-1. I suggest to document further requirements on the kernel in that table.

@YuPengZTE an example with regards to what we want to avoid is that if I use distro X for my HostOS i.e. in my RA2 compliant NFVI, then I'm obliged to use distro X also to build my container images for my workloads.

**Comment by tomkivlin** [comment]
> @peterwoerndle, would you add some examples for easy understanding?

Another example is that some of the specifications we document here will flow into the OVP badge for CNFs, as well as the badge for a Kubernetes platform.  And this is an example of where we would be specifying that those CNFs are not relying on anything other than the bare minimum from a Host OS.

**Comment by peterwoerndle** [comment]
@tomkivlin can we put requirements on the CNFs in an NFVI RA? Strictly speaking the CNF is out of scope of RA2 as per the overview chapter. I think this relates a bit to @fkautz comment with regards to what are the minimum kernel features we expect from the HostOS kernel. We can then add a statement like: _A CNF running on a RA2 compliant architecture is expected to not require additional capabilities from the HostOS kernel._

**Comment by tomkivlin** [comment]
@peterwoerndle I thought part of the output of CNTT was a set of standard interfaces and specifications for what the CNFs would be consuming.  So whilst the CNF isn't in scope, the interfaces from the NFVI/CaaS are in scope and so we will be provided requirements to CNF vendors as to what those interfaces are (and aren't).

**Comment by tomkivlin** [comment]
@peterwoerndle @fkautz can I suggest we merge this one (which is about the Host OS not restricting the container base image) and we can discuss wording to deal with the container base image not putting restrictions/requirements (or if so, what they are) on the Host OS.

**Comment by YuPengZTE** [comment]
Thanks, @peterwoerndle @tomkivlin.

> @tomkivlin can we put requirements on the CNFs in an NFVI RA? Strictly speaking the CNF is out of scope of RA2 as per the overview chapter. I think this relates a bit to @fkautz comment with regards to what are the minimum kernel features we expect from the HostOS kernel. We can then add a statement like: _A CNF running on a RA2 compliant architecture is expected to not require additional capabilities from the HostOS kernel._

This statement is very clear. :+1:

**Pull request merged**
