### PR TITLE
[RA2] Add Special Interest Group level requirements

### LINKED ISSUE #2030: [RA2] new tab to make the mandatory features clear
RA2 should offer a new tab listing all mandatory/optional Kubernetes Features for RC2 (conforming to RA1 Chapter 5).
https://github.com/cntt-n/CNTT/blob/master/doc/ref_arch/openstack/chapters/chapter05.md#5.2

It may somehow duplicate the existing tabs mostly driven by req traceability (project management).
But it would be the best interface for RC2 and the true e2e traceability expected by users
Please see http://testresults.opnfv.org/functest/traceability/

e.g.: [sig-network]:
- Feature:Ingress
- Feature:IPv6DualStackAlphaFeature
- Feature:Federation
- Feature:kubemci
- Feature:NEG
- Feature:Networking-IPv4
- Feature:Networking-IPv6
- Feature:Networking-Performance
- Feature:NetworkPolicy
- Feature:NoSNAT
- Feature:PerformanceDNS
- Feature:SCTP
- ...

Linked to https://github.com/cntt-n/CNTT/issues/2025

### PR DESCRIPTION
**Pull request by collivier**
It enforces the overall requirements traceability to testing,
especially those offered for End-to-End Testing.

It renames chapter06 to chapter07.

It will be completed by additional pull/requests for all the
SIGs.

fixes #2030

Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>

### CODE REVIEW

**Comment by tomkivlin** [comment]
If this is "requirements", wouldn't it be better suited as a table/tables in chapter02?

**Comment by collivier** [comment]
@tomkivlin For my understanding, these tab will convert the requirements listed in chapter02 to Testing and Kubernetes formats. Like Chapter5 in RA1 (e2e traceability).

**Comment by rgstori** [comment]
Hi @collivier, thanks for this, do you have any suggestions for efficiently identifying the SIGs and features within them, that are relevant to RA2? 

For example, is there any hard-and-fast rule allowing us to know exactly what features come from the [NFD SIG](https://github.com/kubernetes-sigs/node-feature-discovery)? (other than just trying to fish them out of [their docs](https://kubernetes-sigs.github.io/node-feature-discovery/v0.8/get-started/features.html) i guess?)

**Comment by collivier** [comment]
@rgstori I would suggest to start from e2e tests. Then you can easily grep sig- and the feature lists. It's even easier in case of the next K8s version (v1.21) as all tests are now linked to a sig ([k8s.io] were removed). I can easily draw all feature tabs, see Functest, once this one is merged.
_(github doesn't manage PR depedencies and this one moves chapters which block all the next one)._

**Review by rgstori — APPROVED** [review]

**Review by rihabbanday — APPROVED** [review]

**Review by karinesevilla — APPROVED** [review]

**Review by pgoyal01 — APPROVED** [review]

**Pull request merged**
