### PR TITLE
[RM Chap8] Hybrid Multi-Cloud - Multi-Cloud Interactions Model - Add Manage Catalog

### PR DESCRIPTION
**Pull request by jbhartley**
Add "Manage Catalog" interaction into the model.

This update includes updates figure references.
The figure updates are separately (and individually) uploaded.

To avoid reference issue, the related figure update pull requests should be approved prior to accepting this change.
Related figure pull requests:
- https://github.com/cntt-n/CNTT/pull/3089
- https://github.com/cntt-n/CNTT/pull/3090
- https://github.com/cntt-n/CNTT/pull/3091
- https://github.com/cntt-n/CNTT/pull/3092
- https://github.com/cntt-n/CNTT/pull/3093

### CODE REVIEW

**Review by pgoyal01 — APPROVED** [review]

**Review by walterkozlowski — APPROVED** [review]

**Comment by karinesevilla** [comment]
@jbhartley The management of the catalog of services should be clarified. 
The Cloud Provider exposes the catalog of services the CSP can consume but the CSP cannot manage the Cloud Provider catalog of services.
The CSP manages the services offered to the end user using the Cloud Provider services.
The Cloud provider and the CSP are responsible of the management of their own catalogues of services, it is the reason why I think  'manage catalog' in the interaction model is confusing.

**Comment by walterkozlowski** [comment]
@karinesevilla, as dis cussed, can you please review and approve if you can.  Thank you.

**Comment by walterkozlowski** [comment]
@jbhartley, there is an outstanding comment from @karinesevilla, please address

**Comment by jbhartley** [comment]
@karinesevilla to:

"The management of the catalog of services should be clarified.
The Cloud Provider exposes the catalog of services the CSP can consume but the CSP cannot manage the Cloud Provider catalog of services.
The CSP manages the services offered to the end user using the Cloud Provider services.
The Cloud provider and the CSP are responsible of the management of their own catalogues of services, it is the reason why I think 'manage catalog' in the interaction model is confusing."

Yes agree with your feedback. I will raise as specific issue to capture and we can get these diagram updates in and then add clarifying wording update done via new issue.

**Comment by walterkozlowski** [comment]
@karinesevilla ,can you now approve this PR, so John can go ahead and implement your commentary in a new PR, see Issue#3218

**Comment by joaoarodrigues** [comment]
@walterkozlowski Activating Reviewer profile

**Comment by CsatariGergely** [comment]
@jbhartley can you please commit the figures in a ppt(x) file, so future editing is possible. 
It should go to the ref_model/artefacts folder with the naming schema of RM-Ch[chapter-number]-[figure titles].

**Review by karinesevilla — APPROVED** [review]

**Pull request merged**
