### PR TITLE
[RI 1 Core] Update Chp 01 for RI

### PR DESCRIPTION
**Pull request by fuqiao123**
I modify this chapter to include more details. However I have trouble seeing the two figures, so not sure what is actually there. Can anyone help adding more details about what is indicated in those figures.

### CODE REVIEW

**Comment by mf4716** [comment]
@fuqiao123 - let's review during the Wed RI call please.  We see one diagram in 1.1.2, but let's look at any specific issues you're having Wed.  I'll hold approval until we meet.

**Comment by rabiabdel** [comment]
@fuqiao123 if you click on fuqiao123-patch-5 above, this will take you to your local brach. then navigate to /doc/ref_impl/cntt-ri/figures and upload the two figures in there. this will automatically include those figures into your PR. Please let me know if this helps.

**Comment by mf4716** [comment]
@fuqiao123  - I'm able to view the images either directly, or using the icon from GitHub (Chrome) that minimizes the image, which after clicking on the image icon it does open the image.

**Comment by rabi-abdel** [comment]
@markshostak @rrajesh70 can we please get this reviewed by you?

**Comment by rabi-abdel** [comment]
@markshostak @rrajesh70 can you please review. if no review received (or objection) by tomorrows, this will be merged.

**Pull request merged**
