### PR TITLE
[RM Ch04]: Removing instances from Ch04

### LINKED ISSUE #1209: [ALL]: NFVI Profile =? Instance Type
RM Chapter 1.4 introduces the definition of NFVI Software and NFVI Hardware profiles along with Instance Type (in Figure 1-1). For me Instance Type is the NFVI Software Profile and NFVI Hardware profile together. In other parts of the document, like in Chapter 4.2 there are mentions of NFVI Profile, which describes the term better. Instance Type, Instance and NFVI * Profile-s are mixed in the whole document. 

I would propose to 
* Rename Instance Type to NFVI Profile in the whole document
* Add a definition of NFVI Profile to Chapter 1.1

### PR DESCRIPTION
**Pull request by EditKoselak**
done until 4.2.2

Partially closes #1209

### CODE REVIEW

**Comment by kedmison** [comment]
@EditKoselak is this still WIP?  If not, can you please remove the tag and replace WIP with RM in the title?

**Comment by EditKoselak** [comment]
Hello @kedmison, yes, we are still working on this. I changed the title, I hope it's OK now:)

**Comment by rabiabdel** [comment]
@EditKoselak please remove WIP label once this is ready for review.

**Comment by rabiabdel** [comment]
@EditKoselak please rebase to master and resolve conflict

**Comment by EditKoselak** [comment]
> @EditKoselak please rebase to master and resolve conflict

thanks, done:)

**Pull request merged**
