### PR TITLE
[RA-1 Ch06] Initial Content on RBAC

### LINKED ISSUE #1123: [RA1 Ch06] Security: content to be updated
Content must to be aligned with RM Chapter 7
Add content specific for OpenStack and VM

### PR DESCRIPTION
**Pull request by yeelinglam**
Fixes #1123

### CODE REVIEW

**Comment by yeelinglam** [comment]
Fixes #1123

**Comment by pgoyal01** [comment]
@rabi-abdel Yeeling Lam is from AT&T and hence I should not be reviewing the PR.

**Comment by manamsamuel** [comment]
Security requirements should also include how "Access Policies" are enforced during authentication, authorisation and token management. 

Access Policy management which is key is missing.

**Comment by pgoyal01** [comment]
@manamsamuel Can you suggest wording for the " how "Access Policies" are enforced during authentication, authorisation and token management" requirement? Thanks

**Comment by karinesevilla** [comment]
@yeelinglam 
In 6.1 Introduction, the text mentions only recommendations, can you add requirements?
Typo: NFVi -> NFVI (we took this convention)
§6.3.1.1
typo: an identity services -> service
Can you change "your entreprise" by "the cloud provider" or something more neutral
§6.3.1.2
"who they claim to be" -> " who he claims to be "
OpenStack Keystone support -> supports
In Keystone token, "your business needs" -> "the business needs", "your operations" -> "operations"
§6.3.1.4
typo (RBAC). system -> (RBAC) system

**Comment by manamsamuel** [comment]
Openstack Access Policies for identity, authentication, authorisation and token management are stored and managed by Openstack policy.json engine. As the policy rule determines under which circumstance API calls are permitted or denied. It is important to ensure this policy engine is secure and only managed by platform admin using well defined RBAC policies.

**Pull request merged**
