### PR TITLE
[RM Ch 4.2.7] Removing "one stop shop" section

### PR DESCRIPTION
**Pull request by walterkozlowski**
This section is seriously out of date and in my view does not belong to Reference Model anymore, now when we have in Anuket a proper Release Management function.  I propose to remove it for Kali and deal with these problems through the Release Management.

### CODE REVIEW

**Comment by walterkozlowski** [comment]
@bfcohen, @pgoyal01, @karinesevilla, @rgstori  - I need your opinion and approval (if you agree) or an advise (if you do not) what to do urgently.  Please respond quickly.

**Comment by walterkozlowski** [comment]
@CsatariGergely, @bfcohen, @pgoyal01, @rgstori: I propose removing this section from RM, where it does not belong now and is not correct anymore.  However, we need some guidance like this.  I propose also copying this contents into the Anuket TSC Technical Discussion wiki run by @CsatariGergely, discussing the compatibility, naming conventions across the whole Anuket there and creating a Wiki document under TSC.  @CsatariGergely, would you agree to take it as a topic there, and to this approach?

**Comment by walterkozlowski** [comment]
@collivier, add your comments as well please

**Comment by CsatariGergely** [comment]
I somewhat agree, that this content is out of date, especially the "One stop shop" part. The forward and backward compatibility is still valid, but it is true, that it is more an Anuket specification release definition content than an RM content. I'm okay with moving the Backward compatibility piece to a wiki page, discuss it on the weekly meetings and add the result to the release pages.

**Review by karinesevilla — APPROVED** [review]

**Review by pgoyal01 — APPROVED** [review]

**Comment by jtwill98** [comment]
It's OK to remove this section for the Kali release.  It should be revisited after Kali and reviewed as the compatibility topic is relevant.

**Review by pgoyal01 — APPROVED** [review]

**Review by jtwill98 — APPROVED** [review]
OK to remove for Kali release, the top of profiles backward and forward compatibility should be revisited for the next release.

**Pull request merged**
