### PR TITLE
[RA2 Ch04] - Container runtime configs. (Issue 1636)

### LINKED ISSUE #1636: [RA2 Ch04] Define configuration parameters of Container runtimes
As it was discussed in the [RA2 meeting on 2020.05.28](https://wiki.lfnetworking.org/display/LN/2020-05-28+-+%5BCNTT+-+RA2%5D+-+Meeting+Agenda+and+Minutes) RA2 should specify the container runtime parameters what are mandatory to set for an RA2 compliant infrastructure.

### PR DESCRIPTION
**Pull request by satishverma1999**
Proposed changes for Issue issue Fixes #1636 .

### CODE REVIEW

**Review by pgoyal01 — APPROVED** [review]

**Review by tomkivlin — COMMENTED** [review]
Looks good - can I suggest that the tables are merged, and the `ra2.crt.002`-`011` are part of the specification, i.e. we specify that those parameters are used even if we're not specifying hte values).

**Comment by satishverma1999** [comment]
> Looks good - can I suggest that the tables are merged, and the `ra2.crt.002`-`011` are part of the specification, i.e. we specify that those parameters are used even if we're not specifying hte values).

Thanks Tom for the comment. It is doable. Let me modify the commit.

**Comment by satishverma1999** [comment]
> > Looks good - can I suggest that the tables are merged, and the `ra2.crt.002`-`011` are part of the specification, i.e. we specify that those parameters are used even if we're not specifying hte values).
> 
> Thanks Tom for the comment. It is doable. Let me modify the commit.

Submitted a new pull request after modifications based on your suggestions. Pls review. 
https://github.com/cntt-n/CNTT/pull/1995

**Comment by tomkivlin** [comment]
> @satishverma1999 Please close this PR #1932 

Why?

**Comment by satishverma1999** [comment]
New PR  (https://github.com/cntt-n/CNTT/pull/1995) is raised to propagate the changes.
So closing this PR.

**Pull request closed without merging**
