### PR TITLE
[RM Ch04] Clarification of e.nfvi.res.cap.00[123]

### LINKED ISSUE #426: [RM Ch4]: Clarifications to the attributes
-	e.nfvi.res.cap.001, 002 and 003: I do not see a meaning in defining a minimum value for these. It is true that there is a minimum value for these but I see it more like an implementation details than an NFVI capability

### PR DESCRIPTION
**Pull request by CsatariGergely**
Clarification of e.nfvi.res.cap.001, e.nfvi.res.cap.002 and e.nfvi.res.cap.003

Fixes #426

### CODE REVIEW

**Comment by markshostak** [comment]
@CsatariGergely Hi Gergely, Please take a look at PR# 520. If you still have concerns, we can address. Thx, -Mark

**Comment by rabiabdel** [comment]
if this is a duplicate, shall we close?

**Comment by CsatariGergely** [comment]
> 
> 
> @CsatariGergely Hi Gergely, Please take a look at PR# 520. If you still have concerns, we can address. Thx, -Mark

#520

**Comment by CsatariGergely** [comment]
#520 fixed this.

**Pull request closed without merging**
