### PR TITLE
[RI1 Ch9]: Removal of broken image link from 9.2.1 Pharos Specification

### PR DESCRIPTION
**Pull request by CsatariGergely**
The referred image no longer exist.

### CODE REVIEW

**Comment by pgoyal01** [comment]
@CsatariGergely instead of deleting should we have the RI1 team (@jayacha) add an appropriate diagram

**Comment by CsatariGergely** [comment]
Both options are okay for me. If @jayacha can provide the figures I can add them. If we do not have the figures we should remove them from the text.

**Comment by walterkozlowski** [comment]
@jayacha , @CsatariGergely  - please resolve

**Comment by CsatariGergely** [comment]
>     * ../figures/ch04_opnfv_lab_topology.jpg"

As a quick fix I've removed the broken reference to ../figures/ch04_opnfv_lab_topology.jpg"

**Review by walterkozlowski — APPROVED** [review]

**Comment by walterkozlowski** [comment]
@pgoyal01, @collivier, @scottsteinbrueck: i suggest approving this fix dobe by @CsatariGergely and closing this PR.

**Pull request merged**
