### PR TITLE
[RM- Ch04 ] 4.3 Networking

### LINKED ISSUE #1037: [RM] Long Term requirements for SDN, Fabric and Networking
as discussed in RM call ( Feb 5th ) , we need to have very solid requirements for SDN, Fabric and Networking part that should be included in next stable release as we believe it is mandated in our RAs

So I will amend what is discussed over the mail ( Just brain dump ) and let roll the ball from here :

-   Define a Terminology 
-	Underlay and overlay Protocols 
-	How to achieve full Programmability fabric and automated Fabric, do we need SDN ?
-	What is neutron limitation in Openstack and what is Networking limitation in K8s
-	CSP requirement and use cases ( The Gaps in Vanilla Openstack )
o	Service Function chaining ( SFC ) and how to achieve it 
o	Underlay and Overlay Automation & Programmability 
o	Security
o	VNF layer 3 requirements
o	In Case of SRIOV,   Fabric automation 
-	Will Fabric be the same regarding VNF / CNF in terms of Protocols?
-	How can we generalize a Fabric and SDN-C ? 

https://etherpad.opnfv.org/p/ZoopMgLK61

### PR DESCRIPTION
**Pull request by ASawwaf**
The networking part should be developed here
Fixes #1037

### CODE REVIEW

**Comment by kedmison** [comment]
@ASawwaf Is this to hold the content for #1037 when it is developed?  if so, then I think the word 'placeholder' is still sufficient, and that we may not need to add the 'WIP' tag.

**Comment by ASawwaf** [comment]
@kedmison either or 
do you mean "on hold label"

I am ok

**Comment by rabi-abdel** [comment]
@walterkozlowski @ASawwaf feel free to start adding the content discussed in #1037 in here.

**Comment by ASawwaf** [comment]
@walterkozlowski @TFredberg @kedmison 
is this the right place to merge the "Network approach" here ??

**Comment by TFredberg** [comment]
@ASawwaf I am not sure that the content of approach.md (that is more of a discussion chapter) is ready to go into a serious part of the RM real documentation and be "released" in Baldy.

**Comment by ASawwaf** [comment]
@TFredberg , I think it ready to merge now in RM but the question here , where is the best place in RM to merge it , is dedicated chapter or ..

**Comment by rabi-abdel** [comment]
This is now covered in https://github.com/cntt-n/CNTT/pull/1535 I will close now.

**Pull request closed without merging**
