### PR TITLE
[RA - Ch01] Roadmap

### PR DESCRIPTION
**Pull request by rabi-abdel**
This is a place holder that will contain roadmap items for discussion during next Reference Architecture Master meeting.

### CODE REVIEW

**Comment by rabi-abdel** [comment]
@bfcohen I have added a diagram for Roadmap. do you mind reviewing it and adding few lines  around the diagram?

**Comment by rabiabdel** [comment]
@bfcohen to add more text around it and will be approved online.

**Comment by rabiabdel** [comment]
@bfcohen added her changes in a different PR. will merge this since it is not blocking anyone.

**Comment by rabiabdel** [comment]
@bfcohen can you please approve this to be merged? i seen you added a separate PR for the content in Chapter 1, so we can merge this and your other PR.

**Pull request merged**
