### PR TITLE
[Chapter 1] VNF vs CNF

### PR DESCRIPTION
**Pull request by xavier-grall**
PR to try to reflect discussion on issue #122 :
  - V-VNFC & C-VNFC definitions addition
  - Minor rewording as proposed in initial PR #123 

And
  - one NFV**i** less...

### CODE REVIEW

**Comment by xavier-grall** [comment]
I'm afraid we open the door for needing to also defines "hybrid VNF", which would be composed by both V-VNFCs and C-VNFCs (H-VNF ? V&C-VNF ?)
But feel free to add V-VNF and C-VNF definitions (and, why not H-VNF ?) ;-)

**Comment by rabi-abdel** [comment]
Hi @xavier-grall , Thank you for creating the PR and getting consolidation to resolve the issues created for this. My I suggest checking with @bfcohen to see if she is OK with the PR to be created to address the issues. Usually she assign issues to individuals to create PR. can you also specify what issue(s) this is trying to solve? Thanks

**Comment by xavier-grall** [comment]
This PR partially solves issues #122 and #198, and should cancel PR #123 
Partially because it only deals with VNF/CNF definitions ambiguity, but not not with the issue on their control/management at the NFVI level (VM hypervisor and container runtime, eg kvm vs docker) and MANO level (VIM and CISM as per ETSI NFV IFA029, eg openstack vs kubernetes).

**Comment by rabiabdel** [comment]
As discussed with @xavier-grall offline. We will close this Pull Request for Now and issues related to this will be discussed in Chapter Meetings for PR creation.

**Pull request closed without merging**
