### PR TITLE
Delete ch03-model-hardware-resources.PNG

### PR DESCRIPTION
**Pull request by tomkivlin**
This is a duplicate of https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/figures/ch03-model-hardware-resources.png (which has the same filename, but with lowercase file extension).

Not sure if it effects anyone else, but it is causing issues with my local git tracking as my OS only sees one of the files, but constantly thinks a modification has happened (i.e. I cannot `git add` or `git restore` the file).  The above file is the one that is referenced in the document, so I think it is safe for this one to be deleted.

### CODE REVIEW

**Comment by pgoyal01** [comment]
@tomkivlin These are 2 different Figures in the chapter 3:

[RM Section 3.3.2](https://github.com/cntt-n/CNTT/blob/tomkivlin-remove-duplicate-png/doc/ref_model/chapters/chapter03.md#332-hardware-infrastructure-manager) has Figure 3-4:
 https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/figures/ch03-model-hardware-resources.png

while [RM Section 3.4](https://github.com/cntt-n/CNTT/blob/tomkivlin-remove-duplicate-png/doc/ref_model/chapters/chapter03.md#34-hardware-infrastructure-resources) has Figure 3-5:
 https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/figures/ch03-model-hardware-resources.PNG.

May I suggest that the latter Figure 3-5 be renamed both in the "figures" directory as well as in [RM 3.4](https://github.com/cntt-n/CNTT/blob/tomkivlin-remove-duplicate-png/doc/ref_model/chapters/chapter03.md#34-hardware-infrastructure-resources) Figure 3-5.

**Review by pgoyal01 — CHANGES_REQUESTED** [review]
@tomkivlin Please do not delete but rename both in the figures directory and in the RM Chapter 3.4 (Figure 3-5).

**Comment by tomkivlin** [comment]
Ah thanks @pgoyal01 I will do that.

**Comment by tomkivlin** [comment]
@pgoyal01 I've just checked again and this is a duplication.  Figure 3-5 in section 3.4 links to:

https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/figures/ch03-model-hardware-manager.png 

and not 

https://github.com/cntt-n/CNTT/blob/master/doc/ref_model/figures/ch03-model-hardware-resources.PNG

I think this PR is correct as it is.

**Review by pgoyal01 — APPROVED** [review]

**Review by walterkozlowski — APPROVED** [review]

**Comment by walterkozlowski** [comment]
After looking into this, I am not sure this is right, @tomkivlin.  The correct place for files is doc/ref_model/figures/
@TFredberg, is this your diagram?  if this is, I suggest having the correct version in doc/ref_model/figures/ directory and making sure that in the document this is referenced.

**Comment by tomkivlin** [comment]
@walterkozlowski both files are already in that location

**Review by CsatariGergely — APPROVED** [review]

**Review by TFredberg — APPROVED** [review]
Yes, the file "ch03-model-hardware-resources.PNG" shall be deleted. 
The content in both files are the same, but the ".PNG" version takes up more white space and when I uploaded it I didn´t understand that the file type was case sensitive.
At the time I added the picture, I could not remove that file by some reason.
@walterkozlowski the files are in the correct directory as I see it.

**Pull request merged**
