### PR TITLE
RA-1 Ch04 Update chapter04.md to fix error with table headings

### LINKED ISSUE #1220: RA-1 Ch04 issues with table headings
Several of the tables in 4.2.x have the following heading for the BIOS parameters of each node:

BIOS/boot Parameter | **Control server**

**Control server** doesn't correspond with the rows of the table which are BIOS/boot Parameter and **Value** - so need to update the tables to fix this error.

### PR DESCRIPTION
**Pull request by iangardner22**
Updated tables to fix heading issue which listed "Control Server" instead of "Value" as second column. 

fixes #1220

### CODE REVIEW

**Comment by iangardner22** [comment]
@pgoyal01 can you tell me if I did this right... please

**Comment by pgoyal01** [comment]
@iangardner22 Yes -- Thanks

**Comment by iangardner22** [comment]
@pgoyal01 I am really not sure what happened here - I spotted in the rich text preview:

4.2.2.4. Storage nodes
BIOS requirements
BIOS requirements | BIOS/boot Parameter | Value | |--------------------|--------------------| | Boot disks |RAID 1 | | | | | …|

**Comment by iangardner22** [comment]
Thanks for the offline tips @pgoyal01  - we should be good to merge once we get the approvals.

**Pull request merged**
