### PR TITLE
[RA2 Appendix] Kubernetes and Kubernetes Cluster capitalization

### LINKED ISSUE #997: [RA2] Ch6 - capitalise Kubernetes
From deep dive in Prague:
6.14
Capitalise kubernetes -> Kubernetes

### PR DESCRIPTION
**Pull request by EditKoselak**
Fixes #997

### CODE REVIEW

**Review by tomkivlin — APPROVED** [review]

**Review by tomkivlin — APPROVED** [review]

**Review by ulikleber — APPROVED** [review]

**Review by rgstori — APPROVED** [review]

**Comment by pgoyal01** [comment]
lower case "cluster" (multiple in some of the Sections):
- [Appendix B-3](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/appendix-b.md#b3-solution-areas); please note that other uses of "cluster" without Kubernetes are capitalised.
- [Chapter 1.4](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter01.md#14-scope)
- [Chapter 2.3](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter02.md#23-kubernetes-architecture-requirements) req.inf.ntw.10
- [Chapter 3.2](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter03.md#322-container-networking-services)
- [Chapter 3.2.3](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter03.md#323-container-storage-services)
- [Chapter 3.2.4](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter03.md#324-kubernetes-application-package-manager)
- [Chapter 4.6](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter04.md#46-storage-components)
- [Chapter 5.1](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#51-introduction)
- [Chapter 5.2](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#52-principles)
- [Chapter 5.9](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#59-secure-platform-metadata)
- - [Chapter 5.11](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#511--run-time-security)
- [Chapter 5.14](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#514--orchestration--container-manager)
- [Chapter 5.16](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#5161-vm-vs-container-isolation)
[Chapter 6.2.2](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter06.md#622-multi-tenancy-and-workload-isolation-with-kubernetes)
- [Chapter 6.3.2](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter06.md#632-multi-tenancy-and-workload-isolation-with-kubernetes)

Appendix B Title, "Vendors" should be lower case

**Comment by EditKoselak** [comment]
> lower case "cluster" (multiple in some of the Sections):
> 
>     * [Appendix B-3](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/appendix-b.md#b3-solution-areas); please note that other uses of "cluster" without Kubernetes are capitalised.
> 
>     * [Chapter 1.4](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter01.md#14-scope)
> 
>     * [Chapter 2.3](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter02.md#23-kubernetes-architecture-requirements) req.inf.ntw.10
> 
>     * [Chapter 3.2](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter03.md#322-container-networking-services)
> 
>     * [Chapter 3.2.3](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter03.md#323-container-storage-services)
> 
>     * [Chapter 3.2.4](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter03.md#324-kubernetes-application-package-manager)
> 
>     * [Chapter 4.6](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter04.md#46-storage-components)
> 
>     * [Chapter 5.1](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#51-introduction)
> 
>     * [Chapter 5.2](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#52-principles)
> 
>     * [Chapter 5.9](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#59-secure-platform-metadata)
> 
>     * * [Chapter 5.11](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#511--run-time-security)
> 
>     * [Chapter 5.14](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#514--orchestration--container-manager)
> 
>     * [Chapter 5.16](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter05.md#5161-vm-vs-container-isolation)
>       [Chapter 6.2.2](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter06.md#622-multi-tenancy-and-workload-isolation-with-kubernetes)
> 
>     * [Chapter 6.3.2](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/chapter06.md#632-multi-tenancy-and-workload-isolation-with-kubernetes)
> 
> 
> Appendix B Title, "Vendors" should be lower case

@pgoyal01, thanks for the comment! We created a new issue to handle this: #2324.
My suggestion is to use uppercase "Cluster" in case of "Kubernetes Cluster", as that is also mentioned in the glossary, and use lowercase "cluster" in other cases. What do you think?

**Comment by pgoyal01** [comment]
@EditKoselak I agree with your proposal except there are cases where the lower case "cluster" is meant to be "Kubernetes Cluster".

**Comment by pgoyal01** [comment]
@EditKoselak 
[B.3](https://github.com/nokia/CNTT/blob/rach6-kubernetes/doc/ref_arch/kubernetes/chapters/appendix-b.md#b3-solution-areas) reference of cluster in the sentence "hard multitenancy : can be defined as workload isolation mechanism in which the workloads do not share the same cluster resources and are isolated at cluster level." is to Kubernetes Cluster and "cluster" should be capitalised.

As suggested by me this needs to be done elsewhere also.

**Comment by EditKoselak** [comment]
@pgoyal01, thank you for the suggestion, we've corrected "cluster" to "Cluster" in case of Kubernetes Cluster.

**Review by pgoyal01 — APPROVED** [review]

**Review by rgstori — APPROVED** [review]

**Pull request merged**
