### PR TITLE
[RM Ch03] Fixes issue#1465

### PR DESCRIPTION
**Pull request by deepanshu1422**
Table 5-7: Virtual Networking Acceleration features ---->Table 5-7: Cloud Infrastructure Platform services.

Also, added following in the table as minimum requirements

Database as a service e.g Cassandra
Queue e.g Rabbit MQ
LB and HA Proxy

### CODE REVIEW

**Comment by kedmison** [comment]
hello @deepanshu1422, the repository is frozen for now while we do proofreading and stabilizing.  So, this PR is placed on hold until the proofreading is done and the repository open for updates again.

**Comment by deepanshu1422** [comment]
In the meantime ,Am I allowed to contribute to other issues in the project in so that you might merge them after you finish
proofreading and stabilising  ?🙂

**Comment by kedmison** [comment]
Yes, PRs are accepted, but they will not be merged until the proofreading phase is complete.

In this particular case, I think there needs to be some discussion on the source issue #1465   itself as I am not sure that there is support for specifying the listed services in the RM as Cloud Infrastructure Platform Services.

**Comment by deepanshu1422** [comment]
Sure, no problem at all...I just love this project and want to be a contributor 😇.

Thanks !

**Pull request merged**
