### PR TITLE
[RI Ch09] Pharos Details in Development Chapter

### LINKED ISSUE #406: [RI1 Ch06] Current Existing Labs details
This issue is to include what labs are available currently (community, approved lab schemes, etc)

### PR DESCRIPTION
**Pull request by rabi-abdel**
Bringing https://github.com/cntt-n/CNTT/pull/810 content by @markbeierl in here and closing original one. (since there was restructuring happening)

Fixes #406

### CODE REVIEW

**Comment by rabi-abdel** [comment]
The Delta between what Paros requires and what is expected by CNTT will need to be covered and addressed.

**Comment by rabi-abdel** [comment]
@fuqiao123 are you ok with this content? this originally created by @markbeierl . Please approve if you would like it to be merged.

**Comment by fuqiao123** [comment]
There are some typo with the numbers of the sub-chapters. I am OK with the rest of the contents. And agree with Rabi we need to look into the delta of Pharos with the requirement of CNTT, otherwise it make no sense to talk about pharos in this RI document

**Comment by rabiabdel** [comment]
@fuqiao123 @mk721p can we get this approved and merged. we can then clean it up.

**Comment by mf4716** [comment]
Current content is okay.   I'll approve, to share my concurrence.  

FYI - over the last few days I've spoken to the NFVBench PTL and he mentioned a dependency on certain NICs to support the TRex traffic generator used by that project.  These NICs are Intel X710 (10G), XXV710 (25G) and XL710 (40G).  Sharing this, as some point in the future we may need to augment the specs referenced to include specific h/w which can support traffic, or load, generators.  CNTT needs a performance solution which does not have a specific h/w manufacturer dependency.  Having said that, while we may utilize NFVBench to benchmark profiles, there is low probability CNTT will require such a tool for Conformanace, or Badging purposes.

**Comment by ASawwaf** [comment]
> Current content is okay. I'll approve, to share my concurrence.
> 
> FYI - over the last few days I've spoken to the NFVBench PTL and he mentioned a dependency on certain NICs to support the TRex traffic generator used by that project. These NICs are Intel X710 (10G), XXV710 (25G) and XL710 (40G). Sharing this, as some point in the future we may need to augment the specs referenced to include specific h/w which can support traffic, or load, generators. CNTT needs a performance solution which does not have a specific h/w manufacturer dependency. Having said that, while we may utilize NFVBench to benchmark profiles, there is low probability CNTT will require such a tool for Conformanace, or Badging purposes.

@mf4716 @rabi-abdel wired we looking for abstraction and at the same time there is a dependency on NIC card ( for testing tool ) :)

**Comment by mf4716** [comment]
> @mf4716 @rabi-abdel wired we looking for abstraction and at the same time there is a dependency on NIC card ( for testing tool ) :)

(Agree.. but, keep reading.) When it comes to tooling, we have to be cognizant of mandatory, recommended, and agnostic, type h/w requirements which enable CNTT, and 3rd party suppliers to achieve compliance expectations.  I ran through an exercise this week, asking questions of various perf tool owners, trying to understand pros/cons/requirements - keeping in mind the entire time, we need a light-weight solution that can be packaged w/ a cookbook to accelerate lab validations.  Requiring suppliers to build-out traffic generators, do cabling, config TOR switches, and possibly even change our h/w to align with traffic tool requirements is neither effective, nor efficient, not to mention cost prohibitive (potentially for support, h/w purchase, etc).   Having said that, I agree that we remain abstract, but be aware that our tangible implementation and conformance runs need to remain light-weight.

**Comment by ASawwaf** [comment]
@mf4716 Thanks, interesting to know the result of the running exercise

**Comment by rabiabdel** [comment]
@ASawwaf in addition to what @mf4716 highlighted, this has been identified here as Gap of which we need to work with OPNFV to fix.hence this content is on ch09.

**Pull request merged**
