### PR TITLE
[RM ch02] profiles figure update

### PR DESCRIPTION
**Pull request by xavier-grall**
Fixes issue #344 (and PR suggested by @ASawwaf in #350 )

I do not find Ulrich id in reviewers list (despite he is co-leader for that chapter), and also any other VNF vendor id

### CODE REVIEW

**Comment by pgoyal01** [comment]
@xavier-grall As the figure is about VNFs, should NMS be included under "Basic" profile? I think we had a similar issue raised once before.

**Comment by xavier-grall** [comment]
@pgoyal01 right, we had a discussion about this and you concluded "I am OK with keeping NMS but we need to define it within Chapter 2 text": https://github.com/cntt-n/CNTT/issues/256#issuecomment-531316272
The text in chapter 2 which defines it is here: 
https://github.com/cntt-n/CNTT/blame/master/doc/ref_model/chapters/chapter02.md#L112
Note: that PR is only for inverting compute and network profiles figure as requested by Rabi

**Comment by pgoyal01** [comment]
@xavier-grall Thanks -- see the mention of NMS. Thnaks

**Comment by ulikleber** [comment]
Figure 2-1 now lists the profiles: basic - CI - NI, while the figure in chapter 8 lists basic - NI - CI.
Could you also add the figure number in chapter 8, please.

**Comment by xavier-grall** [comment]
@ulikleber 
Not sure to understand your comment: this PR inverts CI and NI figures in chapter 2 for having B-NI-CI order as in the entire document, including chapter 8.
Note: chapter 8 link to the new and definitive image file in "figures" directory is also changed.
PR results:
https://github.com/cntt-n/CNTT/blob/xavier-grall-patch-2/doc/ref_model/chapters/chapter02.md#2.3
https://github.com/cntt-n/CNTT/blob/xavier-grall-patch-2/doc/ref_model/chapters/chapter08.md#8.6.2

**Comment by xavier-grall** [comment]
Replaced by PR #555 (to also consider issue #536)

**Pull request closed without merging**
