### PR TITLE
[RM Ch3+4] Moving 4.3 to 3.5.x

### LINKED ISSUE #2367: [RM Ch04] Find home for 4.3 Networking content
Chapter 4 is about profiles and Section 4.3 Networking content would be better located elsewhere  (in say RM Chapter 03)

### PR DESCRIPTION
**Pull request by petorre**
Closes #2367 .

### CODE REVIEW

**Review by pgoyal01 — APPROVED** [review]

**Review by ulikleber — APPROVED** [review]

**Review by walterkozlowski — APPROVED** [review]

**Comment by walterkozlowski** [comment]
@TFredberg and @sureshkrishnan , can you please double check and approve if everything Ok?

**Review by TFredberg — APPROVED** [review]
I think this moves works well.

There are a few things I suggest to be updated before the Kali release and preferably before a merge, but they are all of textual/editorial nature and follows here below:
- Chapter 3.2 have now introduced the term "Virtual Infrastructure Layer" where some content in the Networking chapter in Chapter 3.5 still talks about "SW Virtualisation Layer" and sometimes "Virtualisation Layer" (that was an older name we used) for the same thing. This should be corrected before release.
- Remove "the current" from the first bullet in chapter 3.5.2.
- There are some mentioning of CNTT, that either shall be removed (if that is suitable) or replaced by Anuket. This also include figures 3-6 and 3-9

**Comment by petorre** [comment]
> There are a few things I suggest to be updated before the Kali release and preferably before a merge, but they are all of textual/editorial nature and follows here below:

@TFredberg : Thanks, I did all that in last commits.

**Comment by TFredberg** [comment]
I have updated the figures as needed and uploaded both the .png and the source .pptx to the /figures directory.
This is done through a new PR https://github.com/cntt-n/CNTT/pull/2439
Hope you can update the references to these files so they work when both have been added to the Master branch.

**Comment by petorre** [comment]
> 
> 
> I have updated the figures as needed and uploaded both the .png and the source .pptx to the /figures directory.
> This is done through a new PR #2439
> Hope you can update the references to these files so they work when both have been added to the Master branch.

@TFredberg : I would suggest we get this PR merged (in it for figure file names I only changed "ch4" to "ch3" and updated links in Ch3. Your PR #2439 also changes names so for me is bit complex to know which one is which. Then please update the new Ch3 figures (named exactly the same, or if different then also links to them).

**Comment by TFredberg** [comment]
In the .pptx file first slide I put in the algorithm I used for the file names:
”RM-Ch03_5-” and add the Wanted_Caption_Text
I copied the Caption of your contribution and consequently got the names:
RM-Ch03_5-Networking Reference Model based on the ETSI NFV.png
RM-Ch03_5-Underlay Networking separation examples.png
RM-Ch03_5-SDN Controller relationship examples.png
RM-Ch03_5-Networking Reference Model deployment example.png
If you still feel it is simpler or more robust to upload the files inside your branch, I can send the files in a zip-format to you.

**Comment by petorre** [comment]
> In the .pptx file first slide I put in the algorithm I used for the file names:
> ”RM-Ch03_5-” and add the Wanted_Caption_Text
> I copied the Caption of your contribution and consequently got the names:
> RM-Ch03_5-Networking Reference Model based on the ETSI NFV.png
> RM-Ch03_5-Underlay Networking separation examples.png
> RM-Ch03_5-SDN Controller relationship examples.png
> RM-Ch03_5-Networking Reference Model deployment example.png
> If you still feel it is simpler or more robust to upload the files inside your branch, I can send the files in a zip-format to you.

@TFredberg : Thanks. Now I changed URLs and deleted my .png files. So it should point to your .png files when PR #2439 gets merged.

**Pull request merged**
