### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by burakkazan**
Storage intensive related figures updates.

### CODE REVIEW

**Comment by markshostak** [comment]
Approved, except for ch05_ref_nfvi_sw_profiles_v1.PNG, which requires removal of SDN-C.

**Comment by rabiabdel** [comment]
Hi Everyone, i understand this has been approved today in the meeting. we have decided not to add a storage profile for MVP and therefore, i propose freezing this Pull Request until we do so. @burakkazan are you OK with this conclusion? or do you like to discuss this further in the upcoming meeting?

**Comment by burakkazan** [comment]
> Hi Everyone, i understand this has been approved today in the meeting. we have decided not to add a storage profile for MVP and therefore, i propose freezing this Pull Request until we do so. @burakkazan are you OK with this conclusion? or do you like to discuss this further in the upcoming meeting?

**Comment by burakkazan** [comment]
Hi Rabi, yes in order to add this storage intensive workload category we need to update all of the chapters accordingly which requires allignment, we can freeze it for now.

**Comment by karinesevilla** [comment]
Hi everyone,
I agree to differ the introduction of Storage Intensive profile to a further release of the document

**Comment by rabiabdel** [comment]
Thanks @burakkazan and @karinesevilla for your confirmation. I will close it for now. (it can be reopened for future releases)

**Pull request closed without merging**
