### PR TITLE
[RM-ch02 ]Profiles language updates

### PR DESCRIPTION
**Pull request by xavier-grall**
Fixes and reflects disscussion in #571

### CODE REVIEW

**Comment by xavier-grall** [comment]
@pgoyal01 
Your approval  (or comment if any) would be welcome, so I can add the source figure in artefact directory before merging.
Thank you in advance

**Comment by rabi-abdel** [comment]
@markshostak as a WSL, please review.

**Comment by pgoyal01** [comment]
@xavier-grall The diagrams are OK but the words used (Regular resources, Network-oriented resources and Computing-oriented resources) are not defined within the text. 

Some other observations:

- "require predictable compute performance": since in 2.2 the term "computing" is used can this be "require predictable computing performance"
- "Computing speed and/or predictability (i.e., CPU and RAM sharing level)": is the wording in parentheses for "predictability"; in that case is it the intent to suggest that the "sharing level" may affect "computing performance predictability"? If yes, then can that be clearly stated.

Thanks for asking.

**Comment by xavier-grall** [comment]
@pgoyal01 

> @xavier-grall The diagrams are OK but the words used (Regular resources, Network-oriented resources and Computing-oriented resources) are not defined within the text.

OK, I prefer to remove them since they are redondant with profile names


>     * "require predictable compute performance": since in 2.2 the term "computing" is used can this be "require predictable computing performance"

OK, make sense (moreover, you are better than me for english language ;-)

 
>     * "Computing speed and/or predictability (i.e., CPU and RAM sharing level)": is the wording in parentheses for "predictability"; in that case is it the intent to suggest that the "sharing level" may affect "computing performance predictability"? If yes, then can that be clearly stated.

OK, I will separate speed and predictability

**Comment by xavier-grall** [comment]
@pgoyal01 modifications done, if it's ok thank you for approving

**Comment by xavier-grall** [comment]
A few additional (and final ?) modifications: previous uploaded figures were not correct, another compute/computing rewording, analysis alignment with profiles definition

**Comment by rabi-abdel** [comment]
it still require @markshostak approval as WSL. will keep an eye on it and once he approves it, it will be merged.

**Comment by rabiabdel** [comment]
No need for 48 hours cooling off period as this is minor change.

**Pull request merged**
