### PR TITLE
[RM Ch04]: Adding links ot the ETSI NFV specs

### PR DESCRIPTION
**Pull request by CsatariGergely**

### CODE REVIEW

**Comment by karinesevilla** [comment]
@CsatariGergely 
It should be good to add also the reference to ETSI NFV-TST 008 clause 6 for Host CPU utilization. This metric is specified there.

**Comment by CsatariGergely** [comment]
> 
> 
> @CsatariGergely
> It should be good to add also the reference to ETSI NFV-TST 008 clause 6 for Host CPU utilization. This metric is specified there.

Added

**Comment by CsatariGergely** [comment]
> 
> 
> The ETSI links have versions in them.
> This is probably a good thing, to ensure consistency between Baldy and the ETSI documents at time of Baldy publication.
> 
> Would it be useful to put the version in the text as a reminder that periodically the link targets should be refreshed and re-considered?

Correct, versions added.

**Comment by rabiabdel** [comment]
@kedmison, @karinesevilla please review/approve

**Pull request merged**
