### PR TITLE
[ra2] fixing text references to section and typos

### PR DESCRIPTION
**Pull request by rgstori**

### CODE REVIEW

**Comment by rgstori** [comment]
- chapter 2 - RM references to fix ~ 50 references - @rgstori 
- chapter 4 - RI2 references to fix ~ 30 refs - @CsatariGergely 
- typos chapter 2 3 4 7 - @pgoyal01

**Comment by rgstori** [comment]
linewrap of table content in 
- chapter 2 - @rgstori 
- chapter 4 - @CsatariGergely 
- rest of chapters - @pgoyal01

**Comment by collivier** [comment]
@rgstori I don't get your points RM/RI2 references to fix - From a sphinx state point, they are now all good.

**Comment by collivier** [comment]
Please rebase it - now ra2 and ra1 checks pass successfully

**Review by CsatariGergely — APPROVED** [review]

**Comment by rgstori** [comment]
@collivier this is hopefully the last one for RA2, can you merge it before the final build tonight please?

**Comment by collivier** [comment]
@rgstori it's merged and published.

**Pull request merged**
